/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "ACClearAttrs.h"

static asn_TYPE_member_t asn_MBR_attrs_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Attribute,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_attrs_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_attrs_specs_4 = {
	sizeof(struct ACClearAttrs__attrs),
	offsetof(struct ACClearAttrs__attrs, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_attrs_4 = {
	"attrs",
	"attrs",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_attrs_tags_4,
	sizeof(asn_DEF_attrs_tags_4)
		/sizeof(asn_DEF_attrs_tags_4[0]), /* 1 */
	asn_DEF_attrs_tags_4,	/* Same as above */
	sizeof(asn_DEF_attrs_tags_4)
		/sizeof(asn_DEF_attrs_tags_4[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_attrs_4,
	1,	/* Single element */
	&asn_SPC_attrs_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ACClearAttrs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ACClearAttrs, acIssuer),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_GeneralName,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"acIssuer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ACClearAttrs, acSerial),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"acSerial"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ACClearAttrs, attrs),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_attrs_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"attrs"
		},
};
static const ber_tlv_tag_t asn_DEF_ACClearAttrs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ACClearAttrs_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* acSerial */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* attrs */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* otherName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* rfc822Name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* dNSName */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 }, /* x400Address */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 0, 0, 0 }, /* directoryName */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 0, 0, 0 }, /* ediPartyName */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 0, 0, 0 }, /* uniformResourceIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 0, 0, 0 }, /* iPAddress */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 0, 0, 0 } /* registeredID */
};
static asn_SEQUENCE_specifics_t asn_SPC_ACClearAttrs_specs_1 = {
	sizeof(struct ACClearAttrs),
	offsetof(struct ACClearAttrs, _asn_ctx),
	asn_MAP_ACClearAttrs_tag2el_1,
	11,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ACClearAttrs = {
	"ACClearAttrs",
	"ACClearAttrs",
	&asn_OP_SEQUENCE,
	asn_DEF_ACClearAttrs_tags_1,
	sizeof(asn_DEF_ACClearAttrs_tags_1)
		/sizeof(asn_DEF_ACClearAttrs_tags_1[0]), /* 1 */
	asn_DEF_ACClearAttrs_tags_1,	/* Same as above */
	sizeof(asn_DEF_ACClearAttrs_tags_1)
		/sizeof(asn_DEF_ACClearAttrs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ACClearAttrs_1,
	3,	/* Elements count */
	&asn_SPC_ACClearAttrs_specs_1	/* Additional specs */
};

