/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "AttCertIssuer.h"

static asn_oer_constraints_t asn_OER_type_AttCertIssuer_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_AttCertIssuer_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_AttCertIssuer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AttCertIssuer, choice.v1Form),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GeneralNames,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v1Form"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttCertIssuer, choice.v2Form),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_V2Form,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v2Form"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_AttCertIssuer_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* v1Form */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 } /* v2Form */
};
asn_CHOICE_specifics_t asn_SPC_AttCertIssuer_specs_1 = {
	sizeof(struct AttCertIssuer),
	offsetof(struct AttCertIssuer, _asn_ctx),
	offsetof(struct AttCertIssuer, present),
	sizeof(((struct AttCertIssuer *)0)->present),
	asn_MAP_AttCertIssuer_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AttCertIssuer = {
	"AttCertIssuer",
	"AttCertIssuer",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_AttCertIssuer_constr_1, &asn_PER_type_AttCertIssuer_constr_1, CHOICE_constraint },
	asn_MBR_AttCertIssuer_1,
	2,	/* Elements count */
	&asn_SPC_AttCertIssuer_specs_1	/* Additional specs */
};

