/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AttributeCertificateVersion1"
 * 	found in "asn1/rfc3369-AttributeCertificateVersion1.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "AttributeCertificateInfoV1.h"

static asn_oer_constraints_t asn_OER_type_subject_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_subject_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static int asn_DFL_2_cmp_0(const void *sptr) {
	const AttCertVersionV1_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	long value;
	if(asn_INTEGER2long(st, &value))
		return -1;
	return (value != 0);
}
static int asn_DFL_2_set_0(void **sptr) {
	AttCertVersionV1_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	return asn_long2INTEGER(st, 0);
}
static asn_TYPE_member_t asn_MBR_subject_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1__subject, choice.baseCertificateID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IssuerSerial,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"baseCertificateID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1__subject, choice.subjectName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralNames,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subjectName"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_subject_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* baseCertificateID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* subjectName */
};
static asn_CHOICE_specifics_t asn_SPC_subject_specs_3 = {
	sizeof(struct AttributeCertificateInfoV1__subject),
	offsetof(struct AttributeCertificateInfoV1__subject, _asn_ctx),
	offsetof(struct AttributeCertificateInfoV1__subject, present),
	sizeof(((struct AttributeCertificateInfoV1__subject *)0)->present),
	asn_MAP_subject_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_subject_3 = {
	"subject",
	"subject",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_subject_constr_3, &asn_PER_type_subject_constr_3, CHOICE_constraint },
	asn_MBR_subject_3,
	2,	/* Elements count */
	&asn_SPC_subject_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_attributes_10[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Attribute,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_attributes_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_attributes_specs_10 = {
	sizeof(struct AttributeCertificateInfoV1__attributes),
	offsetof(struct AttributeCertificateInfoV1__attributes, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_attributes_10 = {
	"attributes",
	"attributes",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_attributes_tags_10,
	sizeof(asn_DEF_attributes_tags_10)
		/sizeof(asn_DEF_attributes_tags_10[0]), /* 1 */
	asn_DEF_attributes_tags_10,	/* Same as above */
	sizeof(asn_DEF_attributes_tags_10)
		/sizeof(asn_DEF_attributes_tags_10[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_attributes_10,
	1,	/* Single element */
	&asn_SPC_attributes_specs_10	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_AttributeCertificateInfoV1_1[] = {
	{ ATF_POINTER, 1, offsetof(struct AttributeCertificateInfoV1, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_AttCertVersionV1,
		0,
		{ 0, 0, 0 },
		&asn_DFL_2_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_2_set_0,	/* Set DEFAULT 0 */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1, subject),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_subject_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subject"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1, issuer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GeneralNames,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"issuer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1, signature),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgorithmIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signature"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1, serialNumber),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_CertificateSerialNumber,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serialNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1, attCertValidityPeriod),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AttCertValidityPeriod,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"attCertValidityPeriod"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1, attributes),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_attributes_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"attributes"
		},
	{ ATF_POINTER, 2, offsetof(struct AttributeCertificateInfoV1, issuerUniqueID),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_UniqueIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"issuerUniqueID"
		},
	{ ATF_POINTER, 1, offsetof(struct AttributeCertificateInfoV1, extensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extensions"
		},
};
static const int asn_MAP_AttributeCertificateInfoV1_oms_1[] = { 0, 7, 8 };
static const ber_tlv_tag_t asn_DEF_AttributeCertificateInfoV1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AttributeCertificateInfoV1_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -1, 0 }, /* serialNumber */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 7, 0, 0 }, /* issuerUniqueID */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 4 }, /* issuer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -1, 3 }, /* signature */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -2, 2 }, /* attCertValidityPeriod */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 6, -3, 1 }, /* attributes */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, -4, 0 }, /* extensions */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* baseCertificateID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* subjectName */
};
asn_SEQUENCE_specifics_t asn_SPC_AttributeCertificateInfoV1_specs_1 = {
	sizeof(struct AttributeCertificateInfoV1),
	offsetof(struct AttributeCertificateInfoV1, _asn_ctx),
	asn_MAP_AttributeCertificateInfoV1_tag2el_1,
	10,	/* Count of tags in the map */
	asn_MAP_AttributeCertificateInfoV1_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AttributeCertificateInfoV1 = {
	"AttributeCertificateInfoV1",
	"AttributeCertificateInfoV1",
	&asn_OP_SEQUENCE,
	asn_DEF_AttributeCertificateInfoV1_tags_1,
	sizeof(asn_DEF_AttributeCertificateInfoV1_tags_1)
		/sizeof(asn_DEF_AttributeCertificateInfoV1_tags_1[0]), /* 1 */
	asn_DEF_AttributeCertificateInfoV1_tags_1,	/* Same as above */
	sizeof(asn_DEF_AttributeCertificateInfoV1_tags_1)
		/sizeof(asn_DEF_AttributeCertificateInfoV1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AttributeCertificateInfoV1_1,
	9,	/* Elements count */
	&asn_SPC_AttributeCertificateInfoV1_specs_1	/* Additional specs */
};

