/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "asn1/rfc5280-PKIX1Explicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_Attribute_H_
#define	_Attribute_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttributeType.h"
#include "AttributeValue.h"
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Attribute */
typedef struct Attribute {
	AttributeType_t	 type;
	struct Attribute__values {
		A_SET_OF(AttributeValue_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} values;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Attribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Attribute;
extern asn_SEQUENCE_specifics_t asn_SPC_Attribute_specs_1;
extern asn_TYPE_member_t asn_MBR_Attribute_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Attribute_H_ */
#include <asn_internal.h>
