/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "asn1/rfc5280-PKIX1Explicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "AttributeValue.h"

/*
 * This type is implemented using ANY,
 * so here we adjust the DEF accordingly.
 */
asn_TYPE_descriptor_t asn_DEF_AttributeValue = {
	"AttributeValue",
	"AttributeValue",
	&asn_OP_ANY,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, ANY_constraint },
	0, 0,	/* No members */
	&asn_SPC_ANY_specs	/* Additional specs */
};

