/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AttributeCertificateVersion1"
 * 	found in "asn1/rfc3369-AttributeCertificateVersion1.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_AttributeCertificateV1_H_
#define	_AttributeCertificateV1_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttributeCertificateInfoV1.h"
#include "AlgorithmIdentifier.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AttributeCertificateV1 */
typedef struct AttributeCertificateV1 {
	AttributeCertificateInfoV1_t	 acInfo;
	AlgorithmIdentifier_t	 signatureAlgorithm;
	BIT_STRING_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttributeCertificateV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeCertificateV1;
extern asn_SEQUENCE_specifics_t asn_SPC_AttributeCertificateV1_specs_1;
extern asn_TYPE_member_t asn_MBR_AttributeCertificateV1_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _AttributeCertificateV1_H_ */
#include <asn_internal.h>
