/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_AttributeCertificateInfo_H_
#define	_AttributeCertificateInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttCertVersion.h"
#include "Holder.h"
#include "AttCertIssuer.h"
#include "AlgorithmIdentifier.h"
#include "CertificateSerialNumber.h"
#include "AttCertValidityPeriod.h"
#include "UniqueIdentifier.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Extensions;
struct Attribute;

/* AttributeCertificateInfo */
typedef struct AttributeCertificateInfo {
	AttCertVersion_t	 version;
	Holder_t	 holder;
	AttCertIssuer_t	 issuer;
	AlgorithmIdentifier_t	 signature;
	CertificateSerialNumber_t	 serialNumber;
	AttCertValidityPeriod_t	 attrCertValidityPeriod;
	struct AttributeCertificateInfo__attributes {
		A_SEQUENCE_OF(struct Attribute) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} attributes;
	UniqueIdentifier_t	*issuerUniqueID	/* OPTIONAL */;
	struct Extensions	*extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttributeCertificateInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeCertificateInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_AttributeCertificateInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_AttributeCertificateInfo_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Extensions.h"
#include "Attribute.h"

#endif	/* _AttributeCertificateInfo_H_ */
#include <asn_internal.h>
