/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_AuthenticatedData_H_
#define	_AuthenticatedData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CMSVersion.h"
#include "RecipientInfos.h"
#include "MessageAuthenticationCodeAlgorithm.h"
#include "EncapsulatedContentInfo.h"
#include "MessageAuthenticationCode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OriginatorInfo;
struct DigestAlgorithmIdentifier;
struct AuthAttributes;
struct UnauthAttributes;

/* AuthenticatedData */
typedef struct AuthenticatedData {
	CMSVersion_t	 version;
	struct OriginatorInfo	*originatorInfo	/* OPTIONAL */;
	RecipientInfos_t	 recipientInfos;
	MessageAuthenticationCodeAlgorithm_t	 macAlgorithm;
	struct DigestAlgorithmIdentifier	*digestAlgorithm	/* OPTIONAL */;
	EncapsulatedContentInfo_t	 encapContentInfo;
	struct AuthAttributes	*authAttrs	/* OPTIONAL */;
	MessageAuthenticationCode_t	 mac;
	struct UnauthAttributes	*unauthAttrs	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuthenticatedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthenticatedData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OriginatorInfo.h"
#include "DigestAlgorithmIdentifier.h"
#include "AuthAttributes.h"
#include "UnauthAttributes.h"

#endif	/* _AuthenticatedData_H_ */
#include <asn_internal.h>
