/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXqualified88"
 * 	found in "asn1/rfc3739-PKIXqualified88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_BiometricData_H_
#define	_BiometricData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TypeOfBiometricData.h"
#include "AlgorithmIdentifier.h"
#include <OCTET_STRING.h>
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BiometricData */
typedef struct BiometricData {
	TypeOfBiometricData_t	 typeOfBiometricData;
	AlgorithmIdentifier_t	 hashAlgorithm;
	OCTET_STRING_t	 biometricDataHash;
	IA5String_t	*sourceDataUri	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BiometricData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BiometricData;
extern asn_SEQUENCE_specifics_t asn_SPC_BiometricData_specs_1;
extern asn_TYPE_member_t asn_MBR_BiometricData_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _BiometricData_H_ */
#include <asn_internal.h>
