/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXqualified88"
 * 	found in "asn1/rfc3739-PKIXqualified88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "BiometricData.h"

asn_TYPE_member_t asn_MBR_BiometricData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BiometricData, typeOfBiometricData),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_TypeOfBiometricData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"typeOfBiometricData"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BiometricData, hashAlgorithm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgorithmIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hashAlgorithm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BiometricData, biometricDataHash),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"biometricDataHash"
		},
	{ ATF_POINTER, 1, offsetof(struct BiometricData, sourceDataUri),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sourceDataUri"
		},
};
static const int asn_MAP_BiometricData_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_BiometricData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BiometricData_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* predefinedBiometricType */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 0 }, /* biometricDataHash */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* biometricDataOid */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* hashAlgorithm */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 3, 0, 0 } /* sourceDataUri */
};
asn_SEQUENCE_specifics_t asn_SPC_BiometricData_specs_1 = {
	sizeof(struct BiometricData),
	offsetof(struct BiometricData, _asn_ctx),
	asn_MAP_BiometricData_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_BiometricData_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_BiometricData = {
	"BiometricData",
	"BiometricData",
	&asn_OP_SEQUENCE,
	asn_DEF_BiometricData_tags_1,
	sizeof(asn_DEF_BiometricData_tags_1)
		/sizeof(asn_DEF_BiometricData_tags_1[0]), /* 1 */
	asn_DEF_BiometricData_tags_1,	/* Same as above */
	sizeof(asn_DEF_BiometricData_tags_1)
		/sizeof(asn_DEF_BiometricData_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_BiometricData_1,
	4,	/* Elements count */
	&asn_SPC_BiometricData_specs_1	/* Additional specs */
};

