/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SXGModule"
 * 	found in "asn1/sxg.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_CanSignHttpExchanges_H_
#define	_CanSignHttpExchanges_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CanSignHttpExchanges */
typedef NULL_t	 CanSignHttpExchanges_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CanSignHttpExchanges;
asn_struct_free_f CanSignHttpExchanges_free;
asn_struct_print_f CanSignHttpExchanges_print;
asn_constr_check_f CanSignHttpExchanges_constraint;
ber_type_decoder_f CanSignHttpExchanges_decode_ber;
der_type_encoder_f CanSignHttpExchanges_encode_der;
xer_type_decoder_f CanSignHttpExchanges_decode_xer;
xer_type_encoder_f CanSignHttpExchanges_encode_xer;
oer_type_decoder_f CanSignHttpExchanges_decode_oer;
oer_type_encoder_f CanSignHttpExchanges_encode_oer;
per_type_decoder_f CanSignHttpExchanges_decode_uper;
per_type_encoder_f CanSignHttpExchanges_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CanSignHttpExchanges_H_ */
#include <asn_internal.h>
