/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MicrosoftExtensions"
 * 	found in "asn1/msft.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_CertificateTemplateOID_H_
#define	_CertificateTemplateOID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CertificateTemplateOID */
typedef struct CertificateTemplateOID {
	OBJECT_IDENTIFIER_t	 templateID;
	unsigned long	*templateMajorVersion	/* OPTIONAL */;
	unsigned long	*templateMinorVersion	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertificateTemplateOID_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_templateMajorVersion_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_templateMinorVersion_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CertificateTemplateOID;

#ifdef __cplusplus
}
#endif

#endif	/* _CertificateTemplateOID_H_ */
#include <asn_internal.h>
