/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CertificateTransparencyModule"
 * 	found in "asn1/ct.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_CertificateTransparencyPoison_H_
#define	_CertificateTransparencyPoison_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CertificateTransparencyPoison */
typedef NULL_t	 CertificateTransparencyPoison_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateTransparencyPoison;
asn_struct_free_f CertificateTransparencyPoison_free;
asn_struct_print_f CertificateTransparencyPoison_print;
asn_constr_check_f CertificateTransparencyPoison_constraint;
ber_type_decoder_f CertificateTransparencyPoison_decode_ber;
der_type_encoder_f CertificateTransparencyPoison_encode_der;
xer_type_decoder_f CertificateTransparencyPoison_decode_xer;
xer_type_encoder_f CertificateTransparencyPoison_encode_xer;
oer_type_decoder_f CertificateTransparencyPoison_decode_oer;
oer_type_encoder_f CertificateTransparencyPoison_encode_oer;
per_type_decoder_f CertificateTransparencyPoison_decode_uper;
per_type_encoder_f CertificateTransparencyPoison_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CertificateTransparencyPoison_H_ */
#include <asn_internal.h>
