/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MicrosoftExtensions"
 * 	found in "asn1/msft.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "CertificateTemplateOID.h"

static int
templateMajorVersion_3_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
templateMinorVersion_4_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_templateMajorVersion_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_templateMinorVersion_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static asn_oer_constraints_t asn_OER_type_templateMajorVersion_constr_3 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_templateMajorVersion_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_templateMinorVersion_constr_4 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_templateMinorVersion_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_templateMajorVersion_constr_3 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_templateMajorVersion_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_templateMinorVersion_constr_4 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_templateMinorVersion_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_templateMajorVersion_specs_3 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_templateMajorVersion_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_templateMajorVersion_3 = {
	"templateMajorVersion",
	"templateMajorVersion",
	&asn_OP_NativeInteger,
	asn_DEF_templateMajorVersion_tags_3,
	sizeof(asn_DEF_templateMajorVersion_tags_3)
		/sizeof(asn_DEF_templateMajorVersion_tags_3[0]) - 1, /* 1 */
	asn_DEF_templateMajorVersion_tags_3,	/* Same as above */
	sizeof(asn_DEF_templateMajorVersion_tags_3)
		/sizeof(asn_DEF_templateMajorVersion_tags_3[0]), /* 2 */
	{ &asn_OER_type_templateMajorVersion_constr_3, &asn_PER_type_templateMajorVersion_constr_3, templateMajorVersion_3_constraint },
	0, 0,	/* No members */
	&asn_SPC_templateMajorVersion_specs_3	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_templateMinorVersion_specs_4 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_templateMinorVersion_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_templateMinorVersion_4 = {
	"templateMinorVersion",
	"templateMinorVersion",
	&asn_OP_NativeInteger,
	asn_DEF_templateMinorVersion_tags_4,
	sizeof(asn_DEF_templateMinorVersion_tags_4)
		/sizeof(asn_DEF_templateMinorVersion_tags_4[0]) - 1, /* 1 */
	asn_DEF_templateMinorVersion_tags_4,	/* Same as above */
	sizeof(asn_DEF_templateMinorVersion_tags_4)
		/sizeof(asn_DEF_templateMinorVersion_tags_4[0]), /* 2 */
	{ &asn_OER_type_templateMinorVersion_constr_4, &asn_PER_type_templateMinorVersion_constr_4, templateMinorVersion_4_constraint },
	0, 0,	/* No members */
	&asn_SPC_templateMinorVersion_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CertificateTemplateOID_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CertificateTemplateOID, templateID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"templateID"
		},
	{ ATF_POINTER, 2, offsetof(struct CertificateTemplateOID, templateMajorVersion),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_templateMajorVersion_3,
		0,
		{ &asn_OER_memb_templateMajorVersion_constr_3, &asn_PER_memb_templateMajorVersion_constr_3,  memb_templateMajorVersion_constraint_1 },
		0, 0, /* No default value */
		"templateMajorVersion"
		},
	{ ATF_POINTER, 1, offsetof(struct CertificateTemplateOID, templateMinorVersion),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_templateMinorVersion_4,
		0,
		{ &asn_OER_memb_templateMinorVersion_constr_4, &asn_PER_memb_templateMinorVersion_constr_4,  memb_templateMinorVersion_constraint_1 },
		0, 0, /* No default value */
		"templateMinorVersion"
		},
};
static const int asn_MAP_CertificateTemplateOID_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_CertificateTemplateOID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CertificateTemplateOID_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* templateID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* templateMajorVersion */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* templateMinorVersion */
};
static asn_SEQUENCE_specifics_t asn_SPC_CertificateTemplateOID_specs_1 = {
	sizeof(struct CertificateTemplateOID),
	offsetof(struct CertificateTemplateOID, _asn_ctx),
	asn_MAP_CertificateTemplateOID_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_CertificateTemplateOID_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CertificateTemplateOID = {
	"CertificateTemplateOID",
	"CertificateTemplateOID",
	&asn_OP_SEQUENCE,
	asn_DEF_CertificateTemplateOID_tags_1,
	sizeof(asn_DEF_CertificateTemplateOID_tags_1)
		/sizeof(asn_DEF_CertificateTemplateOID_tags_1[0]), /* 1 */
	asn_DEF_CertificateTemplateOID_tags_1,	/* Same as above */
	sizeof(asn_DEF_CertificateTemplateOID_tags_1)
		/sizeof(asn_DEF_CertificateTemplateOID_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CertificateTemplateOID_1,
	3,	/* Elements count */
	&asn_SPC_CertificateTemplateOID_specs_1	/* Additional specs */
};

