/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_CertificateChoices_H_
#define	_CertificateChoices_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Certificate.h"
#include "ExtendedCertificate.h"
#include "AttributeCertificateV1.h"
#include "AttributeCertificateV2.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CertificateChoices_PR {
	CertificateChoices_PR_NOTHING,	/* No components present */
	CertificateChoices_PR_certificate,
	CertificateChoices_PR_extendedCertificate,
	CertificateChoices_PR_v1AttrCert,
	CertificateChoices_PR_v2AttrCert
} CertificateChoices_PR;

/* CertificateChoices */
typedef struct CertificateChoices {
	CertificateChoices_PR present;
	union CertificateChoices_u {
		Certificate_t	 certificate;
		ExtendedCertificate_t	 extendedCertificate;
		AttributeCertificateV1_t	 v1AttrCert;
		AttributeCertificateV2_t	 v2AttrCert;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertificateChoices_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateChoices;
extern asn_CHOICE_specifics_t asn_SPC_CertificateChoices_specs_1;
extern asn_TYPE_member_t asn_MBR_CertificateChoices_1[4];
extern asn_per_constraints_t asn_PER_type_CertificateChoices_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CertificateChoices_H_ */
#include <asn_internal.h>
