/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "CertificateChoices.h"

static asn_oer_constraints_t asn_OER_type_CertificateChoices_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_CertificateChoices_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_CertificateChoices_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CertificateChoices, choice.certificate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Certificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certificate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertificateChoices, choice.extendedCertificate),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtendedCertificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extendedCertificate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertificateChoices, choice.v1AttrCert),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AttributeCertificateV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v1AttrCert"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertificateChoices, choice.v2AttrCert),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AttributeCertificateV2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v2AttrCert"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_CertificateChoices_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* certificate */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* extendedCertificate */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* v1AttrCert */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 } /* v2AttrCert */
};
asn_CHOICE_specifics_t asn_SPC_CertificateChoices_specs_1 = {
	sizeof(struct CertificateChoices),
	offsetof(struct CertificateChoices, _asn_ctx),
	offsetof(struct CertificateChoices, present),
	sizeof(((struct CertificateChoices *)0)->present),
	asn_MAP_CertificateChoices_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CertificateChoices = {
	"CertificateChoices",
	"CertificateChoices",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_CertificateChoices_constr_1, &asn_PER_type_CertificateChoices_constr_1, CHOICE_constraint },
	asn_MBR_CertificateChoices_1,
	4,	/* Elements count */
	&asn_SPC_CertificateChoices_specs_1	/* Additional specs */
};

