/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "Clearance.h"

static asn_TYPE_member_t asn_MBR_securityCategories_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SecurityCategory,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_securityCategories_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_securityCategories_specs_4 = {
	sizeof(struct Clearance__securityCategories),
	offsetof(struct Clearance__securityCategories, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_securityCategories_4 = {
	"securityCategories",
	"securityCategories",
	&asn_OP_SET_OF,
	asn_DEF_securityCategories_tags_4,
	sizeof(asn_DEF_securityCategories_tags_4)
		/sizeof(asn_DEF_securityCategories_tags_4[0]) - 1, /* 1 */
	asn_DEF_securityCategories_tags_4,	/* Same as above */
	sizeof(asn_DEF_securityCategories_tags_4)
		/sizeof(asn_DEF_securityCategories_tags_4[0]), /* 2 */
	{ 0, 0, SET_OF_constraint },
	asn_MBR_securityCategories_4,
	1,	/* Single element */
	&asn_SPC_securityCategories_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Clearance_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Clearance, policyId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"policyId"
		},
	{ ATF_POINTER, 2, offsetof(struct Clearance, classList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ClassList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"classList"
		},
	{ ATF_POINTER, 1, offsetof(struct Clearance, securityCategories),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_securityCategories_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"securityCategories"
		},
};
static const int asn_MAP_Clearance_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_Clearance_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Clearance_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* policyId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* classList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* securityCategories */
};
static asn_SEQUENCE_specifics_t asn_SPC_Clearance_specs_1 = {
	sizeof(struct Clearance),
	offsetof(struct Clearance, _asn_ctx),
	asn_MAP_Clearance_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_Clearance_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Clearance = {
	"Clearance",
	"Clearance",
	&asn_OP_SEQUENCE,
	asn_DEF_Clearance_tags_1,
	sizeof(asn_DEF_Clearance_tags_1)
		/sizeof(asn_DEF_Clearance_tags_1[0]), /* 1 */
	asn_DEF_Clearance_tags_1,	/* Same as above */
	sizeof(asn_DEF_Clearance_tags_1)
		/sizeof(asn_DEF_Clearance_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Clearance_1,
	3,	/* Elements count */
	&asn_SPC_Clearance_specs_1	/* Additional specs */
};

