/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "asn1/rfc5280-PKIX1Explicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_CountryName_H_
#define	_CountryName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NumericString.h>
#include <PrintableString.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CountryName_PR {
	CountryName_PR_NOTHING,	/* No components present */
	CountryName_PR_x121_dcc_code,
	CountryName_PR_iso_3166_alpha2_code
} CountryName_PR;

/* CountryName */
typedef struct CountryName {
	CountryName_PR present;
	union CountryName_u {
		NumericString_t	 x121_dcc_code;
		PrintableString_t	 iso_3166_alpha2_code;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CountryName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CountryName;
extern asn_CHOICE_specifics_t asn_SPC_CountryName_specs_1;
extern asn_TYPE_member_t asn_MBR_CountryName_1[2];
extern asn_per_constraints_t asn_PER_type_CountryName_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CountryName_H_ */
#include <asn_internal.h>
