/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_CryptographicMessageSyntax_Signature_H_
#define	_CryptographicMessageSyntax_Signature_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Signature */
typedef BIT_STRING_t	 CryptographicMessageSyntax_Signature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CryptographicMessageSyntax_Signature;
asn_struct_free_f CryptographicMessageSyntax_Signature_free;
asn_struct_print_f CryptographicMessageSyntax_Signature_print;
asn_constr_check_f CryptographicMessageSyntax_Signature_constraint;
ber_type_decoder_f CryptographicMessageSyntax_Signature_decode_ber;
der_type_encoder_f CryptographicMessageSyntax_Signature_encode_der;
xer_type_decoder_f CryptographicMessageSyntax_Signature_decode_xer;
xer_type_encoder_f CryptographicMessageSyntax_Signature_encode_xer;
oer_type_decoder_f CryptographicMessageSyntax_Signature_decode_oer;
oer_type_encoder_f CryptographicMessageSyntax_Signature_encode_oer;
per_type_decoder_f CryptographicMessageSyntax_Signature_decode_uper;
per_type_encoder_f CryptographicMessageSyntax_Signature_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CryptographicMessageSyntax_Signature_H_ */
#include <asn_internal.h>
