/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "DigestedData.h"

static asn_TYPE_member_t asn_MBR_DigestedData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DigestedData, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_CMSVersion,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DigestedData, digestAlgorithm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DigestAlgorithmIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"digestAlgorithm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DigestedData, encapContentInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EncapsulatedContentInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"encapContentInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DigestedData, digest),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_Digest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"digest"
		},
};
static const ber_tlv_tag_t asn_DEF_DigestedData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DigestedData_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, 0, 0 }, /* digest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 1 }, /* digestAlgorithm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 0 } /* encapContentInfo */
};
static asn_SEQUENCE_specifics_t asn_SPC_DigestedData_specs_1 = {
	sizeof(struct DigestedData),
	offsetof(struct DigestedData, _asn_ctx),
	asn_MAP_DigestedData_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DigestedData = {
	"DigestedData",
	"DigestedData",
	&asn_OP_SEQUENCE,
	asn_DEF_DigestedData_tags_1,
	sizeof(asn_DEF_DigestedData_tags_1)
		/sizeof(asn_DEF_DigestedData_tags_1[0]), /* 1 */
	asn_DEF_DigestedData_tags_1,	/* Same as above */
	sizeof(asn_DEF_DigestedData_tags_1)
		/sizeof(asn_DEF_DigestedData_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DigestedData_1,
	4,	/* Elements count */
	&asn_SPC_DigestedData_specs_1	/* Additional specs */
};

