/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "asn1/rfc5280-PKIX1Explicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "DistinguishedName.h"

/*
 * This type is implemented using RDNSequence,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_DistinguishedName_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_DistinguishedName = {
	"DistinguishedName",
	"DistinguishedName",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_DistinguishedName_tags_1,
	sizeof(asn_DEF_DistinguishedName_tags_1)
		/sizeof(asn_DEF_DistinguishedName_tags_1[0]), /* 1 */
	asn_DEF_DistinguishedName_tags_1,	/* Same as above */
	sizeof(asn_DEF_DistinguishedName_tags_1)
		/sizeof(asn_DEF_DistinguishedName_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_RDNSequence_1,
	1,	/* Single element */
	&asn_SPC_RDNSequence_specs_1	/* Additional specs */
};

