/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Algorithms2008"
 * 	found in "asn1/rfc5480-PKIX1Algorithms2008.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "DSAPublicKey.h"

/*
 * This type is implemented using INTEGER,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_DSAPublicKey_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
asn_TYPE_descriptor_t asn_DEF_DSAPublicKey = {
	"DSAPublicKey",
	"DSAPublicKey",
	&asn_OP_INTEGER,
	asn_DEF_DSAPublicKey_tags_1,
	sizeof(asn_DEF_DSAPublicKey_tags_1)
		/sizeof(asn_DEF_DSAPublicKey_tags_1[0]), /* 1 */
	asn_DEF_DSAPublicKey_tags_1,	/* Same as above */
	sizeof(asn_DEF_DSAPublicKey_tags_1)
		/sizeof(asn_DEF_DSAPublicKey_tags_1[0]), /* 1 */
	{ 0, 0, INTEGER_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

