/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Algorithms2008"
 * 	found in "asn1/rfc5480-PKIX1Algorithms2008.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "DSS-Parms.h"

static asn_TYPE_member_t asn_MBR_DSS_Parms_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DSS_Parms, p),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"p"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DSS_Parms, q),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"q"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DSS_Parms, g),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"g"
		},
};
static const ber_tlv_tag_t asn_DEF_DSS_Parms_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DSS_Parms_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* p */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 1 }, /* q */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 0 } /* g */
};
static asn_SEQUENCE_specifics_t asn_SPC_DSS_Parms_specs_1 = {
	sizeof(struct DSS_Parms),
	offsetof(struct DSS_Parms, _asn_ctx),
	asn_MAP_DSS_Parms_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DSS_Parms = {
	"DSS-Parms",
	"DSS-Parms",
	&asn_OP_SEQUENCE,
	asn_DEF_DSS_Parms_tags_1,
	sizeof(asn_DEF_DSS_Parms_tags_1)
		/sizeof(asn_DEF_DSS_Parms_tags_1[0]), /* 1 */
	asn_DEF_DSS_Parms_tags_1,	/* Same as above */
	sizeof(asn_DEF_DSS_Parms_tags_1)
		/sizeof(asn_DEF_DSS_Parms_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DSS_Parms_1,
	3,	/* Elements count */
	&asn_SPC_DSS_Parms_specs_1	/* Additional specs */
};

