/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Algorithms2008"
 * 	found in "asn1/rfc5480-PKIX1Algorithms2008.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "ECParameters.h"

static asn_oer_constraints_t asn_OER_type_ECParameters_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ECParameters_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ECParameters_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ECParameters, choice.namedCurve),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"namedCurve"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ECParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* namedCurve */
};
static asn_CHOICE_specifics_t asn_SPC_ECParameters_specs_1 = {
	sizeof(struct ECParameters),
	offsetof(struct ECParameters, _asn_ctx),
	offsetof(struct ECParameters, present),
	sizeof(((struct ECParameters *)0)->present),
	asn_MAP_ECParameters_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ECParameters = {
	"ECParameters",
	"ECParameters",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ECParameters_constr_1, &asn_PER_type_ECParameters_constr_1, CHOICE_constraint },
	asn_MBR_ECParameters_1,
	1,	/* Elements count */
	&asn_SPC_ECParameters_specs_1	/* Additional specs */
};

