/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Algorithms2008"
 * 	found in "asn1/rfc5480-PKIX1Algorithms2008.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_ECPoint_H_
#define	_ECPoint_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ECPoint */
typedef OCTET_STRING_t	 ECPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECPoint;
asn_struct_free_f ECPoint_free;
asn_struct_print_f ECPoint_print;
asn_constr_check_f ECPoint_constraint;
ber_type_decoder_f ECPoint_decode_ber;
der_type_encoder_f ECPoint_encode_der;
xer_type_decoder_f ECPoint_decode_xer;
xer_type_encoder_f ECPoint_encode_xer;
oer_type_decoder_f ECPoint_decode_oer;
oer_type_encoder_f ECPoint_encode_oer;
per_type_decoder_f ECPoint_decode_uper;
per_type_encoder_f ECPoint_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ECPoint_H_ */
#include <asn_internal.h>
