/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_EncapsulatedContentInfo_H_
#define	_EncapsulatedContentInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ContentType.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EncapsulatedContentInfo */
typedef struct EncapsulatedContentInfo {
	ContentType_t	 eContentType;
	OCTET_STRING_t	*eContent	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EncapsulatedContentInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncapsulatedContentInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_EncapsulatedContentInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_EncapsulatedContentInfo_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EncapsulatedContentInfo_H_ */
#include <asn_internal.h>
