/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EntrustExtensions"
 * 	found in "asn1/entrust.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_EntrustInfoFlags_H_
#define	_EntrustInfoFlags_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EntrustInfoFlags {
	EntrustInfoFlags_keyUpdateAllowed	= 1,
	EntrustInfoFlags_pKIXCertificate	= 2
} e_EntrustInfoFlags;

/* EntrustInfoFlags */
typedef BIT_STRING_t	 EntrustInfoFlags_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EntrustInfoFlags;
asn_struct_free_f EntrustInfoFlags_free;
asn_struct_print_f EntrustInfoFlags_print;
asn_constr_check_f EntrustInfoFlags_constraint;
ber_type_decoder_f EntrustInfoFlags_decode_ber;
der_type_encoder_f EntrustInfoFlags_encode_der;
xer_type_decoder_f EntrustInfoFlags_decode_xer;
xer_type_encoder_f EntrustInfoFlags_encode_xer;
oer_type_decoder_f EntrustInfoFlags_decode_oer;
oer_type_encoder_f EntrustInfoFlags_encode_oer;
per_type_decoder_f EntrustInfoFlags_decode_uper;
per_type_encoder_f EntrustInfoFlags_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EntrustInfoFlags_H_ */
#include <asn_internal.h>
