/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_EnvelopedData_H_
#define	_EnvelopedData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CMSVersion.h"
#include "RecipientInfos.h"
#include "EncryptedContentInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OriginatorInfo;
struct UnprotectedAttributes;

/* EnvelopedData */
typedef struct EnvelopedData {
	CMSVersion_t	 version;
	struct OriginatorInfo	*originatorInfo	/* OPTIONAL */;
	RecipientInfos_t	 recipientInfos;
	EncryptedContentInfo_t	 encryptedContentInfo;
	struct UnprotectedAttributes	*unprotectedAttrs	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EnvelopedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnvelopedData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OriginatorInfo.h"
#include "UnprotectedAttributes.h"

#endif	/* _EnvelopedData_H_ */
#include <asn_internal.h>
