/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_ExtendedCertificate_H_
#define	_ExtendedCertificate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ExtendedCertificateInfo.h"
#include "SignatureAlgorithmIdentifier.h"
#include "CryptographicMessageSyntax_Signature.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtendedCertificate */
typedef struct ExtendedCertificate {
	ExtendedCertificateInfo_t	 extendedCertificateInfo;
	SignatureAlgorithmIdentifier_t	 signatureAlgorithm;
	CryptographicMessageSyntax_Signature_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExtendedCertificate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtendedCertificate;
extern asn_SEQUENCE_specifics_t asn_SPC_ExtendedCertificate_specs_1;
extern asn_TYPE_member_t asn_MBR_ExtendedCertificate_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ExtendedCertificate_H_ */
#include <asn_internal.h>
