/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "asn1/rfc5280-PKIX1Explicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "ExtensionAttribute.h"

static int
memb_extension_attribute_type_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 256)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_extension_attribute_type_constr_2 CC_NOTUSED = {
	{ 2, 1 }	/* (0..256) */,
	-1};
static asn_per_constraints_t asn_PER_memb_extension_attribute_type_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  256 }	/* (0..256) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ExtensionAttribute_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ExtensionAttribute, extension_attribute_type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_extension_attribute_type_constr_2, &asn_PER_memb_extension_attribute_type_constr_2,  memb_extension_attribute_type_constraint_1 },
		0, 0, /* No default value */
		"extension-attribute-type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ExtensionAttribute, extension_attribute_value),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ANY,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extension-attribute-value"
		},
};
static const ber_tlv_tag_t asn_DEF_ExtensionAttribute_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ExtensionAttribute_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* extension-attribute-type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* extension-attribute-value */
};
asn_SEQUENCE_specifics_t asn_SPC_ExtensionAttribute_specs_1 = {
	sizeof(struct ExtensionAttribute),
	offsetof(struct ExtensionAttribute, _asn_ctx),
	asn_MAP_ExtensionAttribute_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ExtensionAttribute = {
	"ExtensionAttribute",
	"ExtensionAttribute",
	&asn_OP_SEQUENCE,
	asn_DEF_ExtensionAttribute_tags_1,
	sizeof(asn_DEF_ExtensionAttribute_tags_1)
		/sizeof(asn_DEF_ExtensionAttribute_tags_1[0]), /* 1 */
	asn_DEF_ExtensionAttribute_tags_1,	/* Same as above */
	sizeof(asn_DEF_ExtensionAttribute_tags_1)
		/sizeof(asn_DEF_ExtensionAttribute_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ExtensionAttribute_1,
	2,	/* Elements count */
	&asn_SPC_ExtensionAttribute_specs_1	/* Additional specs */
};

