/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "asn1/rfc5280-PKIX1Implicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "GeneralName.h"

static asn_oer_constraints_t asn_OER_type_GeneralName_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_GeneralName_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  8 }	/* (0..8) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_GeneralName_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GeneralName, choice.otherName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AnotherName,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"otherName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GeneralName, choice.rfc822Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rfc822Name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GeneralName, choice.dNSName),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dNSName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GeneralName, choice.x400Address),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ORAddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"x400Address"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GeneralName, choice.directoryName),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"directoryName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GeneralName, choice.ediPartyName),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EDIPartyName,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ediPartyName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GeneralName, choice.uniformResourceIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uniformResourceIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GeneralName, choice.iPAddress),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iPAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GeneralName, choice.registeredID),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"registeredID"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_GeneralName_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* otherName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rfc822Name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dNSName */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* x400Address */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* directoryName */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ediPartyName */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* uniformResourceIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* iPAddress */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* registeredID */
};
asn_CHOICE_specifics_t asn_SPC_GeneralName_specs_1 = {
	sizeof(struct GeneralName),
	offsetof(struct GeneralName, _asn_ctx),
	offsetof(struct GeneralName, present),
	sizeof(((struct GeneralName *)0)->present),
	asn_MAP_GeneralName_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_GeneralName = {
	"GeneralName",
	"GeneralName",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_GeneralName_constr_1, &asn_PER_type_GeneralName_constr_1, CHOICE_constraint },
	asn_MBR_GeneralName_1,
	9,	/* Elements count */
	&asn_SPC_GeneralName_specs_1	/* Additional specs */
};

