/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "asn1/rfc5280-PKIX1Implicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_GeneralSubtree_H_
#define	_GeneralSubtree_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GeneralName.h"
#include "BaseDistance.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GeneralSubtree */
typedef struct GeneralSubtree {
	GeneralName_t	 base;
	BaseDistance_t	*minimum	/* DEFAULT 0 */;
	BaseDistance_t	*maximum	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GeneralSubtree_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GeneralSubtree;
extern asn_SEQUENCE_specifics_t asn_SPC_GeneralSubtree_specs_1;
extern asn_TYPE_member_t asn_MBR_GeneralSubtree_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _GeneralSubtree_H_ */
#include <asn_internal.h>
