/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "Holder.h"

asn_TYPE_member_t asn_MBR_Holder_1[] = {
	{ ATF_POINTER, 3, offsetof(struct Holder, baseCertificateID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IssuerSerial,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"baseCertificateID"
		},
	{ ATF_POINTER, 2, offsetof(struct Holder, entityName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralNames,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"entityName"
		},
	{ ATF_POINTER, 1, offsetof(struct Holder, objectDigestInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObjectDigestInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"objectDigestInfo"
		},
};
static const int asn_MAP_Holder_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_Holder_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Holder_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* baseCertificateID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* entityName */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* objectDigestInfo */
};
asn_SEQUENCE_specifics_t asn_SPC_Holder_specs_1 = {
	sizeof(struct Holder),
	offsetof(struct Holder, _asn_ctx),
	asn_MAP_Holder_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_Holder_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Holder = {
	"Holder",
	"Holder",
	&asn_OP_SEQUENCE,
	asn_DEF_Holder_tags_1,
	sizeof(asn_DEF_Holder_tags_1)
		/sizeof(asn_DEF_Holder_tags_1[0]), /* 1 */
	asn_DEF_Holder_tags_1,	/* Same as above */
	sizeof(asn_DEF_Holder_tags_1)
		/sizeof(asn_DEF_Holder_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Holder_1,
	3,	/* Elements count */
	&asn_SPC_Holder_specs_1	/* Additional specs */
};

