/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "IetfAttrSyntax.h"

static asn_oer_constraints_t asn_OER_type_Member_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_Member_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Member_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IetfAttrSyntax__values__Member, choice.octets),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"octets"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IetfAttrSyntax__values__Member, choice.oid),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"oid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IetfAttrSyntax__values__Member, choice.string),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"string"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_4[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* octets */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, 0, 0 }, /* oid */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 2, 0, 0 } /* string */
};
static asn_CHOICE_specifics_t asn_SPC_Member_specs_4 = {
	sizeof(struct IetfAttrSyntax__values__Member),
	offsetof(struct IetfAttrSyntax__values__Member, _asn_ctx),
	offsetof(struct IetfAttrSyntax__values__Member, present),
	sizeof(((struct IetfAttrSyntax__values__Member *)0)->present),
	asn_MAP_Member_tag2el_4,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_4 = {
	"CHOICE",
	"CHOICE",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Member_constr_4, &asn_PER_type_Member_constr_4, CHOICE_constraint },
	asn_MBR_Member_4,
	3,	/* Elements count */
	&asn_SPC_Member_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_values_3[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Member_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_values_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_values_specs_3 = {
	sizeof(struct IetfAttrSyntax__values),
	offsetof(struct IetfAttrSyntax__values, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_values_3 = {
	"values",
	"values",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_values_tags_3,
	sizeof(asn_DEF_values_tags_3)
		/sizeof(asn_DEF_values_tags_3[0]), /* 1 */
	asn_DEF_values_tags_3,	/* Same as above */
	sizeof(asn_DEF_values_tags_3)
		/sizeof(asn_DEF_values_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_values_3,
	1,	/* Single element */
	&asn_SPC_values_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_IetfAttrSyntax_1[] = {
	{ ATF_POINTER, 1, offsetof(struct IetfAttrSyntax, policyAuthority),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralNames,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"policyAuthority"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IetfAttrSyntax, values),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_values_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"values"
		},
};
static const int asn_MAP_IetfAttrSyntax_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_IetfAttrSyntax_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IetfAttrSyntax_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* values */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* policyAuthority */
};
static asn_SEQUENCE_specifics_t asn_SPC_IetfAttrSyntax_specs_1 = {
	sizeof(struct IetfAttrSyntax),
	offsetof(struct IetfAttrSyntax, _asn_ctx),
	asn_MAP_IetfAttrSyntax_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_IetfAttrSyntax_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IetfAttrSyntax = {
	"IetfAttrSyntax",
	"IetfAttrSyntax",
	&asn_OP_SEQUENCE,
	asn_DEF_IetfAttrSyntax_tags_1,
	sizeof(asn_DEF_IetfAttrSyntax_tags_1)
		/sizeof(asn_DEF_IetfAttrSyntax_tags_1[0]), /* 1 */
	asn_DEF_IetfAttrSyntax_tags_1,	/* Same as above */
	sizeof(asn_DEF_IetfAttrSyntax_tags_1)
		/sizeof(asn_DEF_IetfAttrSyntax_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IetfAttrSyntax_1,
	2,	/* Elements count */
	&asn_SPC_IetfAttrSyntax_specs_1	/* Additional specs */
};

