/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "IssuerSerial.h"

asn_TYPE_member_t asn_MBR_IssuerSerial_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IssuerSerial, issuer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GeneralNames,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"issuer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IssuerSerial, serial),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_CertificateSerialNumber,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serial"
		},
	{ ATF_POINTER, 1, offsetof(struct IssuerSerial, issuerUID),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_UniqueIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"issuerUID"
		},
};
static const int asn_MAP_IssuerSerial_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_IssuerSerial_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IssuerSerial_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* serial */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, 0, 0 }, /* issuerUID */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* issuer */
};
asn_SEQUENCE_specifics_t asn_SPC_IssuerSerial_specs_1 = {
	sizeof(struct IssuerSerial),
	offsetof(struct IssuerSerial, _asn_ctx),
	asn_MAP_IssuerSerial_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_IssuerSerial_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IssuerSerial = {
	"IssuerSerial",
	"IssuerSerial",
	&asn_OP_SEQUENCE,
	asn_DEF_IssuerSerial_tags_1,
	sizeof(asn_DEF_IssuerSerial_tags_1)
		/sizeof(asn_DEF_IssuerSerial_tags_1[0]), /* 1 */
	asn_DEF_IssuerSerial_tags_1,	/* Same as above */
	sizeof(asn_DEF_IssuerSerial_tags_1)
		/sizeof(asn_DEF_IssuerSerial_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IssuerSerial_1,
	3,	/* Elements count */
	&asn_SPC_IssuerSerial_specs_1	/* Additional specs */
};

