/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CABFSelectedAttributeTypes"
 * 	found in "asn1/cabfev.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_JurisdictionStateOrProvinceName_H_
#define	_JurisdictionStateOrProvinceName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <TeletexString.h>
#include <PrintableString.h>
#include <UniversalString.h>
#include <UTF8String.h>
#include <BMPString.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum JurisdictionStateOrProvinceName_PR {
	JurisdictionStateOrProvinceName_PR_NOTHING,	/* No components present */
	JurisdictionStateOrProvinceName_PR_teletexString,
	JurisdictionStateOrProvinceName_PR_printableString,
	JurisdictionStateOrProvinceName_PR_universalString,
	JurisdictionStateOrProvinceName_PR_utf8String,
	JurisdictionStateOrProvinceName_PR_bmpString
} JurisdictionStateOrProvinceName_PR;

/* JurisdictionStateOrProvinceName */
typedef struct JurisdictionStateOrProvinceName {
	JurisdictionStateOrProvinceName_PR present;
	union JurisdictionStateOrProvinceName_u {
		TeletexString_t	 teletexString;
		PrintableString_t	 printableString;
		UniversalString_t	 universalString;
		UTF8String_t	 utf8String;
		BMPString_t	 bmpString;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} JurisdictionStateOrProvinceName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_JurisdictionStateOrProvinceName;

#ifdef __cplusplus
}
#endif

#endif	/* _JurisdictionStateOrProvinceName_H_ */
#include <asn_internal.h>
