/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "KEKRecipientInfo.h"

asn_TYPE_member_t asn_MBR_KEKRecipientInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct KEKRecipientInfo, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_CMSVersion,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct KEKRecipientInfo, kekid),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_KEKIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"kekid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct KEKRecipientInfo, keyEncryptionAlgorithm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_KeyEncryptionAlgorithmIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"keyEncryptionAlgorithm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct KEKRecipientInfo, encryptedKey),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_EncryptedKey,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"encryptedKey"
		},
};
static const ber_tlv_tag_t asn_DEF_KEKRecipientInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_KEKRecipientInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, 0, 0 }, /* encryptedKey */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 1 }, /* kekid */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 0 } /* keyEncryptionAlgorithm */
};
asn_SEQUENCE_specifics_t asn_SPC_KEKRecipientInfo_specs_1 = {
	sizeof(struct KEKRecipientInfo),
	offsetof(struct KEKRecipientInfo, _asn_ctx),
	asn_MAP_KEKRecipientInfo_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_KEKRecipientInfo = {
	"KEKRecipientInfo",
	"KEKRecipientInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_KEKRecipientInfo_tags_1,
	sizeof(asn_DEF_KEKRecipientInfo_tags_1)
		/sizeof(asn_DEF_KEKRecipientInfo_tags_1[0]), /* 1 */
	asn_DEF_KEKRecipientInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_KEKRecipientInfo_tags_1)
		/sizeof(asn_DEF_KEKRecipientInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_KEKRecipientInfo_1,
	4,	/* Elements count */
	&asn_SPC_KEKRecipientInfo_specs_1	/* Additional specs */
};

