/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_KEKRecipientInfo_H_
#define	_KEKRecipientInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CMSVersion.h"
#include "KEKIdentifier.h"
#include "KeyEncryptionAlgorithmIdentifier.h"
#include "EncryptedKey.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* KEKRecipientInfo */
typedef struct KEKRecipientInfo {
	CMSVersion_t	 version;
	KEKIdentifier_t	 kekid;
	KeyEncryptionAlgorithmIdentifier_t	 keyEncryptionAlgorithm;
	EncryptedKey_t	 encryptedKey;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} KEKRecipientInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KEKRecipientInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_KEKRecipientInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_KEKRecipientInfo_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _KEKRecipientInfo_H_ */
#include <asn_internal.h>
