/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "KeyAgreeRecipientIdentifier.h"

static asn_oer_constraints_t asn_OER_type_KeyAgreeRecipientIdentifier_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_KeyAgreeRecipientIdentifier_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_KeyAgreeRecipientIdentifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct KeyAgreeRecipientIdentifier, choice.issuerAndSerialNumber),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_IssuerAndSerialNumber,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"issuerAndSerialNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct KeyAgreeRecipientIdentifier, choice.rKeyId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RecipientKeyIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rKeyId"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_KeyAgreeRecipientIdentifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* issuerAndSerialNumber */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 } /* rKeyId */
};
asn_CHOICE_specifics_t asn_SPC_KeyAgreeRecipientIdentifier_specs_1 = {
	sizeof(struct KeyAgreeRecipientIdentifier),
	offsetof(struct KeyAgreeRecipientIdentifier, _asn_ctx),
	offsetof(struct KeyAgreeRecipientIdentifier, present),
	sizeof(((struct KeyAgreeRecipientIdentifier *)0)->present),
	asn_MAP_KeyAgreeRecipientIdentifier_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_KeyAgreeRecipientIdentifier = {
	"KeyAgreeRecipientIdentifier",
	"KeyAgreeRecipientIdentifier",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_KeyAgreeRecipientIdentifier_constr_1, &asn_PER_type_KeyAgreeRecipientIdentifier_constr_1, CHOICE_constraint },
	asn_MBR_KeyAgreeRecipientIdentifier_1,
	2,	/* Elements count */
	&asn_SPC_KeyAgreeRecipientIdentifier_specs_1	/* Additional specs */
};

