/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "asn1/rfc2560-OCSP.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_KeyHash_H_
#define	_KeyHash_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* KeyHash */
typedef OCTET_STRING_t	 KeyHash_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KeyHash;
asn_struct_free_f KeyHash_free;
asn_struct_print_f KeyHash_print;
asn_constr_check_f KeyHash_constraint;
ber_type_decoder_f KeyHash_decode_ber;
der_type_encoder_f KeyHash_encode_der;
xer_type_decoder_f KeyHash_decode_xer;
xer_type_encoder_f KeyHash_encode_xer;
oer_type_decoder_f KeyHash_decode_oer;
oer_type_encoder_f KeyHash_encode_oer;
per_type_decoder_f KeyHash_decode_uper;
per_type_encoder_f KeyHash_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _KeyHash_H_ */
#include <asn_internal.h>
