/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LogotypeCertExtn"
 * 	found in "asn1/rfc3709-LogotypeCertExtn.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_LogotypeInfo_H_
#define	_LogotypeInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LogotypeData.h"
#include "LogotypeReference.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LogotypeInfo_PR {
	LogotypeInfo_PR_NOTHING,	/* No components present */
	LogotypeInfo_PR_direct,
	LogotypeInfo_PR_indirect
} LogotypeInfo_PR;

/* LogotypeInfo */
typedef struct LogotypeInfo {
	LogotypeInfo_PR present;
	union LogotypeInfo_u {
		LogotypeData_t	 direct;
		LogotypeReference_t	 indirect;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LogotypeInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LogotypeInfo;
extern asn_CHOICE_specifics_t asn_SPC_LogotypeInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_LogotypeInfo_1[2];
extern asn_per_constraints_t asn_PER_type_LogotypeInfo_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LogotypeInfo_H_ */
#include <asn_internal.h>
