/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LogotypeCertExtn"
 * 	found in "asn1/rfc3709-LogotypeCertExtn.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "LogotypeDetails.h"

static int
memb_logotypeHash_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_logotypeURI_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_logotypeHash_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..MAX)) */};
static asn_per_constraints_t asn_PER_type_logotypeHash_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  1,  0 }	/* (SIZE(1..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_logotypeURI_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..MAX)) */};
static asn_per_constraints_t asn_PER_type_logotypeURI_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  1,  0 }	/* (SIZE(1..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_logotypeHash_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..MAX)) */};
static asn_per_constraints_t asn_PER_memb_logotypeHash_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  1,  0 }	/* (SIZE(1..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_logotypeURI_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..MAX)) */};
static asn_per_constraints_t asn_PER_memb_logotypeURI_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  1,  0 }	/* (SIZE(1..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_logotypeHash_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HashAlgAndValue,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_logotypeHash_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_logotypeHash_specs_3 = {
	sizeof(struct LogotypeDetails__logotypeHash),
	offsetof(struct LogotypeDetails__logotypeHash, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_logotypeHash_3 = {
	"logotypeHash",
	"logotypeHash",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_logotypeHash_tags_3,
	sizeof(asn_DEF_logotypeHash_tags_3)
		/sizeof(asn_DEF_logotypeHash_tags_3[0]), /* 1 */
	asn_DEF_logotypeHash_tags_3,	/* Same as above */
	sizeof(asn_DEF_logotypeHash_tags_3)
		/sizeof(asn_DEF_logotypeHash_tags_3[0]), /* 1 */
	{ &asn_OER_type_logotypeHash_constr_3, &asn_PER_type_logotypeHash_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_logotypeHash_3,
	1,	/* Single element */
	&asn_SPC_logotypeHash_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_logotypeURI_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_logotypeURI_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_logotypeURI_specs_5 = {
	sizeof(struct LogotypeDetails__logotypeURI),
	offsetof(struct LogotypeDetails__logotypeURI, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_logotypeURI_5 = {
	"logotypeURI",
	"logotypeURI",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_logotypeURI_tags_5,
	sizeof(asn_DEF_logotypeURI_tags_5)
		/sizeof(asn_DEF_logotypeURI_tags_5[0]), /* 1 */
	asn_DEF_logotypeURI_tags_5,	/* Same as above */
	sizeof(asn_DEF_logotypeURI_tags_5)
		/sizeof(asn_DEF_logotypeURI_tags_5[0]), /* 1 */
	{ &asn_OER_type_logotypeURI_constr_5, &asn_PER_type_logotypeURI_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_logotypeURI_5,
	1,	/* Single element */
	&asn_SPC_logotypeURI_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LogotypeDetails_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LogotypeDetails, mediaType),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mediaType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LogotypeDetails, logotypeHash),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_logotypeHash_3,
		0,
		{ &asn_OER_memb_logotypeHash_constr_3, &asn_PER_memb_logotypeHash_constr_3,  memb_logotypeHash_constraint_1 },
		0, 0, /* No default value */
		"logotypeHash"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LogotypeDetails, logotypeURI),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_logotypeURI_5,
		0,
		{ &asn_OER_memb_logotypeURI_constr_5, &asn_PER_memb_logotypeURI_constr_5,  memb_logotypeURI_constraint_1 },
		0, 0, /* No default value */
		"logotypeURI"
		},
};
static const ber_tlv_tag_t asn_DEF_LogotypeDetails_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LogotypeDetails_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 1 }, /* logotypeHash */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 0 }, /* logotypeURI */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 0, 0, 0 } /* mediaType */
};
asn_SEQUENCE_specifics_t asn_SPC_LogotypeDetails_specs_1 = {
	sizeof(struct LogotypeDetails),
	offsetof(struct LogotypeDetails, _asn_ctx),
	asn_MAP_LogotypeDetails_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LogotypeDetails = {
	"LogotypeDetails",
	"LogotypeDetails",
	&asn_OP_SEQUENCE,
	asn_DEF_LogotypeDetails_tags_1,
	sizeof(asn_DEF_LogotypeDetails_tags_1)
		/sizeof(asn_DEF_LogotypeDetails_tags_1[0]), /* 1 */
	asn_DEF_LogotypeDetails_tags_1,	/* Same as above */
	sizeof(asn_DEF_LogotypeDetails_tags_1)
		/sizeof(asn_DEF_LogotypeDetails_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LogotypeDetails_1,
	3,	/* Elements count */
	&asn_SPC_LogotypeDetails_specs_1	/* Additional specs */
};

