/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LogotypeCertExtn"
 * 	found in "asn1/rfc3709-LogotypeCertExtn.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_LogotypeData_H_
#define	_LogotypeData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LogotypeImage;
struct LogotypeAudio;

/* LogotypeData */
typedef struct LogotypeData {
	struct LogotypeData__image {
		A_SEQUENCE_OF(struct LogotypeImage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *image;
	struct LogotypeData__audio {
		A_SEQUENCE_OF(struct LogotypeAudio) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *audio;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LogotypeData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LogotypeData;
extern asn_SEQUENCE_specifics_t asn_SPC_LogotypeData_specs_1;
extern asn_TYPE_member_t asn_MBR_LogotypeData_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LogotypeImage.h"
#include "LogotypeAudio.h"

#endif	/* _LogotypeData_H_ */
#include <asn_internal.h>
