/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LogotypeCertExtn"
 * 	found in "asn1/rfc3709-LogotypeCertExtn.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_LogotypeExtn_H_
#define	_LogotypeExtn_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LogotypeInfo;
struct OtherLogotypeInfo;

/* LogotypeExtn */
typedef struct LogotypeExtn {
	struct LogotypeExtn__communityLogos {
		A_SEQUENCE_OF(struct LogotypeInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *communityLogos;
	struct LogotypeInfo	*issuerLogo	/* OPTIONAL */;
	struct LogotypeInfo	*subjectLogo	/* OPTIONAL */;
	struct LogotypeExtn__otherLogos {
		A_SEQUENCE_OF(struct OtherLogotypeInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *otherLogos;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LogotypeExtn_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LogotypeExtn;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LogotypeInfo.h"
#include "OtherLogotypeInfo.h"

#endif	/* _LogotypeExtn_H_ */
#include <asn_internal.h>
