/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LogotypeCertExtn"
 * 	found in "asn1/rfc3709-LogotypeCertExtn.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_LogotypeImage_H_
#define	_LogotypeImage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LogotypeDetails.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LogotypeImageInfo;

/* LogotypeImage */
typedef struct LogotypeImage {
	LogotypeDetails_t	 imageDetails;
	struct LogotypeImageInfo	*imageInfo	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LogotypeImage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LogotypeImage;
extern asn_SEQUENCE_specifics_t asn_SPC_LogotypeImage_specs_1;
extern asn_TYPE_member_t asn_MBR_LogotypeImage_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LogotypeImageInfo.h"

#endif	/* _LogotypeImage_H_ */
#include <asn_internal.h>
