/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LogotypeCertExtn"
 * 	found in "asn1/rfc3709-LogotypeCertExtn.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "LogotypeImage.h"

asn_TYPE_member_t asn_MBR_LogotypeImage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LogotypeImage, imageDetails),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LogotypeDetails,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"imageDetails"
		},
	{ ATF_POINTER, 1, offsetof(struct LogotypeImage, imageInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LogotypeImageInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"imageInfo"
		},
};
static const int asn_MAP_LogotypeImage_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_LogotypeImage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LogotypeImage_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* imageDetails */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 0 } /* imageInfo */
};
asn_SEQUENCE_specifics_t asn_SPC_LogotypeImage_specs_1 = {
	sizeof(struct LogotypeImage),
	offsetof(struct LogotypeImage, _asn_ctx),
	asn_MAP_LogotypeImage_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_LogotypeImage_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LogotypeImage = {
	"LogotypeImage",
	"LogotypeImage",
	&asn_OP_SEQUENCE,
	asn_DEF_LogotypeImage_tags_1,
	sizeof(asn_DEF_LogotypeImage_tags_1)
		/sizeof(asn_DEF_LogotypeImage_tags_1[0]), /* 1 */
	asn_DEF_LogotypeImage_tags_1,	/* Same as above */
	sizeof(asn_DEF_LogotypeImage_tags_1)
		/sizeof(asn_DEF_LogotypeImage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LogotypeImage_1,
	2,	/* Elements count */
	&asn_SPC_LogotypeImage_specs_1	/* Additional specs */
};

