/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1-PSS-OAEP-Algorithms"
 * 	found in "asn1/rfc4055-PKIX1-PSS-OAEP-Algorithms.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_MaskGenAlgorithm_H_
#define	_MaskGenAlgorithm_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AlgorithmIdentifier.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MaskGenAlgorithm */
typedef AlgorithmIdentifier_t	 MaskGenAlgorithm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MaskGenAlgorithm;
asn_struct_free_f MaskGenAlgorithm_free;
asn_struct_print_f MaskGenAlgorithm_print;
asn_constr_check_f MaskGenAlgorithm_constraint;
ber_type_decoder_f MaskGenAlgorithm_decode_ber;
der_type_encoder_f MaskGenAlgorithm_encode_der;
xer_type_decoder_f MaskGenAlgorithm_decode_xer;
xer_type_encoder_f MaskGenAlgorithm_encode_xer;
oer_type_decoder_f MaskGenAlgorithm_decode_oer;
oer_type_encoder_f MaskGenAlgorithm_encode_oer;
per_type_decoder_f MaskGenAlgorithm_decode_uper;
per_type_encoder_f MaskGenAlgorithm_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MaskGenAlgorithm_H_ */
#include <asn_internal.h>
