/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "ObjectDigestInfo.h"

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_digestedObjectType_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_digestedObjectType_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_digestedObjectType_value2enum_2[] = {
	{ 0,	9,	"publicKey" },
	{ 1,	13,	"publicKeyCert" },
	{ 2,	16,	"otherObjectTypes" }
};
static const unsigned int asn_MAP_digestedObjectType_enum2value_2[] = {
	2,	/* otherObjectTypes(2) */
	0,	/* publicKey(0) */
	1	/* publicKeyCert(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_digestedObjectType_specs_2 = {
	asn_MAP_digestedObjectType_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_digestedObjectType_enum2value_2,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_digestedObjectType_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_digestedObjectType_2 = {
	"digestedObjectType",
	"digestedObjectType",
	&asn_OP_ENUMERATED,
	asn_DEF_digestedObjectType_tags_2,
	sizeof(asn_DEF_digestedObjectType_tags_2)
		/sizeof(asn_DEF_digestedObjectType_tags_2[0]), /* 1 */
	asn_DEF_digestedObjectType_tags_2,	/* Same as above */
	sizeof(asn_DEF_digestedObjectType_tags_2)
		/sizeof(asn_DEF_digestedObjectType_tags_2[0]), /* 1 */
	{ &asn_OER_type_digestedObjectType_constr_2, &asn_PER_type_digestedObjectType_constr_2, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_digestedObjectType_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ObjectDigestInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectDigestInfo, digestedObjectType),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_digestedObjectType_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"digestedObjectType"
		},
	{ ATF_POINTER, 1, offsetof(struct ObjectDigestInfo, otherObjectTypeID),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"otherObjectTypeID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectDigestInfo, digestAlgorithm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgorithmIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"digestAlgorithm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectDigestInfo, objectDigest),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"objectDigest"
		},
};
static const int asn_MAP_ObjectDigestInfo_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_ObjectDigestInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ObjectDigestInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 3, 0, 0 }, /* objectDigest */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, 0, 0 }, /* otherObjectTypeID */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 0, 0, 0 }, /* digestedObjectType */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 } /* digestAlgorithm */
};
asn_SEQUENCE_specifics_t asn_SPC_ObjectDigestInfo_specs_1 = {
	sizeof(struct ObjectDigestInfo),
	offsetof(struct ObjectDigestInfo, _asn_ctx),
	asn_MAP_ObjectDigestInfo_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_ObjectDigestInfo_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ObjectDigestInfo = {
	"ObjectDigestInfo",
	"ObjectDigestInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_ObjectDigestInfo_tags_1,
	sizeof(asn_DEF_ObjectDigestInfo_tags_1)
		/sizeof(asn_DEF_ObjectDigestInfo_tags_1[0]), /* 1 */
	asn_DEF_ObjectDigestInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_ObjectDigestInfo_tags_1)
		/sizeof(asn_DEF_ObjectDigestInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ObjectDigestInfo_1,
	4,	/* Elements count */
	&asn_SPC_ObjectDigestInfo_specs_1	/* Additional specs */
};

