/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "asn1/rfc2560-OCSP.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_OcspNoCheckValue_H_
#define	_OcspNoCheckValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OcspNoCheckValue */
typedef NULL_t	 OcspNoCheckValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OcspNoCheckValue;
asn_struct_free_f OcspNoCheckValue_free;
asn_struct_print_f OcspNoCheckValue_print;
asn_constr_check_f OcspNoCheckValue_constraint;
ber_type_decoder_f OcspNoCheckValue_decode_ber;
der_type_encoder_f OcspNoCheckValue_encode_der;
xer_type_decoder_f OcspNoCheckValue_decode_xer;
xer_type_encoder_f OcspNoCheckValue_encode_xer;
oer_type_decoder_f OcspNoCheckValue_decode_oer;
oer_type_encoder_f OcspNoCheckValue_encode_oer;
per_type_decoder_f OcspNoCheckValue_decode_uper;
per_type_encoder_f OcspNoCheckValue_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _OcspNoCheckValue_H_ */
#include <asn_internal.h>
