/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "asn1/rfc2560-OCSP.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "OCSPRequest.h"

static asn_TYPE_member_t asn_MBR_OCSPRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OCSPRequest, tbsRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TBSRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tbsRequest"
		},
	{ ATF_POINTER, 1, offsetof(struct OCSPRequest, optionalSignature),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCSP_Signature,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"optionalSignature"
		},
};
static const int asn_MAP_OCSPRequest_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_OCSPRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_OCSPRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* tbsRequest */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 } /* optionalSignature */
};
static asn_SEQUENCE_specifics_t asn_SPC_OCSPRequest_specs_1 = {
	sizeof(struct OCSPRequest),
	offsetof(struct OCSPRequest, _asn_ctx),
	asn_MAP_OCSPRequest_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_OCSPRequest_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_OCSPRequest = {
	"OCSPRequest",
	"OCSPRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_OCSPRequest_tags_1,
	sizeof(asn_DEF_OCSPRequest_tags_1)
		/sizeof(asn_DEF_OCSPRequest_tags_1[0]), /* 1 */
	asn_DEF_OCSPRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_OCSPRequest_tags_1)
		/sizeof(asn_DEF_OCSPRequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_OCSPRequest_1,
	2,	/* Elements count */
	&asn_SPC_OCSPRequest_specs_1	/* Additional specs */
};

