/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "asn1/rfc2560-OCSP.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_OCSPRequest_H_
#define	_OCSPRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TBSRequest.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Signature;

/* OCSPRequest */
typedef struct OCSPRequest {
	TBSRequest_t	 tbsRequest;
	struct Signature	*optionalSignature	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OCSPRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OCSPRequest;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OCSP_Signature.h"

#endif	/* _OCSPRequest_H_ */
#include <asn_internal.h>
