/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "asn1/rfc2560-OCSP.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "OCSPResponseStatus.h"

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_OCSPResponseStatus_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_OCSPResponseStatus_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_OCSPResponseStatus_value2enum_1[] = {
	{ 0,	10,	"successful" },
	{ 1,	16,	"malformedRequest" },
	{ 2,	13,	"internalError" },
	{ 3,	8,	"tryLater" },
	{ 5,	11,	"sigRequired" },
	{ 6,	12,	"unauthorized" }
};
static const unsigned int asn_MAP_OCSPResponseStatus_enum2value_1[] = {
	2,	/* internalError(2) */
	1,	/* malformedRequest(1) */
	4,	/* sigRequired(5) */
	0,	/* successful(0) */
	3,	/* tryLater(3) */
	5	/* unauthorized(6) */
};
const asn_INTEGER_specifics_t asn_SPC_OCSPResponseStatus_specs_1 = {
	asn_MAP_OCSPResponseStatus_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_OCSPResponseStatus_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_OCSPResponseStatus_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_OCSPResponseStatus = {
	"OCSPResponseStatus",
	"OCSPResponseStatus",
	&asn_OP_ENUMERATED,
	asn_DEF_OCSPResponseStatus_tags_1,
	sizeof(asn_DEF_OCSPResponseStatus_tags_1)
		/sizeof(asn_DEF_OCSPResponseStatus_tags_1[0]), /* 1 */
	asn_DEF_OCSPResponseStatus_tags_1,	/* Same as above */
	sizeof(asn_DEF_OCSPResponseStatus_tags_1)
		/sizeof(asn_DEF_OCSPResponseStatus_tags_1[0]), /* 1 */
	{ &asn_OER_type_OCSPResponseStatus_constr_1, &asn_PER_type_OCSPResponseStatus_constr_1, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_OCSPResponseStatus_specs_1	/* Additional specs */
};

