/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "OriginatorInfo.h"

asn_TYPE_member_t asn_MBR_OriginatorInfo_1[] = {
	{ ATF_POINTER, 2, offsetof(struct OriginatorInfo, certs),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CertificateSet,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certs"
		},
	{ ATF_POINTER, 1, offsetof(struct OriginatorInfo, crls),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CertificateRevocationLists,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crls"
		},
};
static const int asn_MAP_OriginatorInfo_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_OriginatorInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_OriginatorInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* certs */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* crls */
};
asn_SEQUENCE_specifics_t asn_SPC_OriginatorInfo_specs_1 = {
	sizeof(struct OriginatorInfo),
	offsetof(struct OriginatorInfo, _asn_ctx),
	asn_MAP_OriginatorInfo_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_OriginatorInfo_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_OriginatorInfo = {
	"OriginatorInfo",
	"OriginatorInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_OriginatorInfo_tags_1,
	sizeof(asn_DEF_OriginatorInfo_tags_1)
		/sizeof(asn_DEF_OriginatorInfo_tags_1[0]), /* 1 */
	asn_DEF_OriginatorInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_OriginatorInfo_tags_1)
		/sizeof(asn_DEF_OriginatorInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_OriginatorInfo_1,
	2,	/* Elements count */
	&asn_SPC_OriginatorInfo_specs_1	/* Additional specs */
};

