/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_OriginatorInfo_H_
#define	_OriginatorInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CertificateSet;
struct CertificateRevocationLists;

/* OriginatorInfo */
typedef struct OriginatorInfo {
	struct CertificateSet	*certs	/* OPTIONAL */;
	struct CertificateRevocationLists	*crls	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OriginatorInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OriginatorInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_OriginatorInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_OriginatorInfo_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CertificateSet.h"
#include "CertificateRevocationLists.h"

#endif	/* _OriginatorInfo_H_ */
#include <asn_internal.h>
