/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_OriginatorPublicKey_H_
#define	_OriginatorPublicKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AlgorithmIdentifier.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OriginatorPublicKey */
typedef struct OriginatorPublicKey {
	AlgorithmIdentifier_t	 algorithm;
	BIT_STRING_t	 publicKey;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OriginatorPublicKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OriginatorPublicKey;
extern asn_SEQUENCE_specifics_t asn_SPC_OriginatorPublicKey_specs_1;
extern asn_TYPE_member_t asn_MBR_OriginatorPublicKey_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _OriginatorPublicKey_H_ */
#include <asn_internal.h>
