/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "asn1/rfc5280-PKIX1Explicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_PhysicalDeliveryOfficeNumber_H_
#define	_PhysicalDeliveryOfficeNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PDSParameter.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PhysicalDeliveryOfficeNumber */
typedef PDSParameter_t	 PhysicalDeliveryOfficeNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhysicalDeliveryOfficeNumber;
asn_struct_free_f PhysicalDeliveryOfficeNumber_free;
asn_struct_print_f PhysicalDeliveryOfficeNumber_print;
asn_constr_check_f PhysicalDeliveryOfficeNumber_constraint;
ber_type_decoder_f PhysicalDeliveryOfficeNumber_decode_ber;
der_type_encoder_f PhysicalDeliveryOfficeNumber_encode_der;
xer_type_decoder_f PhysicalDeliveryOfficeNumber_decode_xer;
xer_type_encoder_f PhysicalDeliveryOfficeNumber_encode_xer;
oer_type_decoder_f PhysicalDeliveryOfficeNumber_decode_oer;
oer_type_encoder_f PhysicalDeliveryOfficeNumber_encode_oer;
per_type_decoder_f PhysicalDeliveryOfficeNumber_decode_uper;
per_type_encoder_f PhysicalDeliveryOfficeNumber_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PhysicalDeliveryOfficeNumber_H_ */
#include <asn_internal.h>
