/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "asn1/rfc5280-PKIX1Explicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_PKIX1Explicit88_StreetAddress_H_
#define	_PKIX1Explicit88_StreetAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PDSParameter.h"

#ifdef __cplusplus
extern "C" {
#endif

/* StreetAddress */
typedef PDSParameter_t	 PKIX1Explicit88_StreetAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKIX1Explicit88_StreetAddress;
asn_struct_free_f PKIX1Explicit88_StreetAddress_free;
asn_struct_print_f PKIX1Explicit88_StreetAddress_print;
asn_constr_check_f PKIX1Explicit88_StreetAddress_constraint;
ber_type_decoder_f PKIX1Explicit88_StreetAddress_decode_ber;
der_type_encoder_f PKIX1Explicit88_StreetAddress_encode_der;
xer_type_decoder_f PKIX1Explicit88_StreetAddress_decode_xer;
xer_type_encoder_f PKIX1Explicit88_StreetAddress_encode_xer;
oer_type_decoder_f PKIX1Explicit88_StreetAddress_decode_oer;
oer_type_encoder_f PKIX1Explicit88_StreetAddress_encode_oer;
per_type_decoder_f PKIX1Explicit88_StreetAddress_decode_uper;
per_type_encoder_f PKIX1Explicit88_StreetAddress_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PKIX1Explicit88_StreetAddress_H_ */
#include <asn_internal.h>
