/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "asn1/rfc5280-PKIX1Implicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "PolicyMappings.h"

static asn_oer_constraints_t asn_OER_type_PolicyMappings_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..MAX)) */};
static asn_per_constraints_t asn_PER_type_PolicyMappings_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  1,  0 }	/* (SIZE(1..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Member_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PolicyMappings__Member, issuerDomainPolicy),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_CertPolicyId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"issuerDomainPolicy"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PolicyMappings__Member, subjectDomainPolicy),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_CertPolicyId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subjectDomainPolicy"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 1 }, /* issuerDomainPolicy */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, -1, 0 } /* subjectDomainPolicy */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_2 = {
	sizeof(struct PolicyMappings__Member),
	offsetof(struct PolicyMappings__Member, _asn_ctx),
	asn_MAP_Member_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_2 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_2,
	sizeof(asn_DEF_Member_tags_2)
		/sizeof(asn_DEF_Member_tags_2[0]), /* 1 */
	asn_DEF_Member_tags_2,	/* Same as above */
	sizeof(asn_DEF_Member_tags_2)
		/sizeof(asn_DEF_Member_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_2,
	2,	/* Elements count */
	&asn_SPC_Member_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_PolicyMappings_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_PolicyMappings_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_PolicyMappings_specs_1 = {
	sizeof(struct PolicyMappings),
	offsetof(struct PolicyMappings, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_PolicyMappings = {
	"PolicyMappings",
	"PolicyMappings",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_PolicyMappings_tags_1,
	sizeof(asn_DEF_PolicyMappings_tags_1)
		/sizeof(asn_DEF_PolicyMappings_tags_1[0]), /* 1 */
	asn_DEF_PolicyMappings_tags_1,	/* Same as above */
	sizeof(asn_DEF_PolicyMappings_tags_1)
		/sizeof(asn_DEF_PolicyMappings_tags_1[0]), /* 1 */
	{ &asn_OER_type_PolicyMappings_constr_1, &asn_PER_type_PolicyMappings_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_PolicyMappings_1,
	1,	/* Single element */
	&asn_SPC_PolicyMappings_specs_1	/* Additional specs */
};

