/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OtherAttributesModule"
 * 	found in "asn1/otherattrs.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_PostalString_H_
#define	_PostalString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <TeletexString.h>
#include <PrintableString.h>
#include <UniversalString.h>
#include <UTF8String.h>
#include <BMPString.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PostalString_PR {
	PostalString_PR_NOTHING,	/* No components present */
	PostalString_PR_teletexString,
	PostalString_PR_printableString,
	PostalString_PR_universalString,
	PostalString_PR_utf8String,
	PostalString_PR_bmpString
} PostalString_PR;

/* PostalString */
typedef struct PostalString {
	PostalString_PR present;
	union PostalString_u {
		TeletexString_t	 teletexString;
		PrintableString_t	 printableString;
		UniversalString_t	 universalString;
		UTF8String_t	 utf8String;
		BMPString_t	 bmpString;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PostalString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PostalString;
extern asn_CHOICE_specifics_t asn_SPC_PostalString_specs_1;
extern asn_TYPE_member_t asn_MBR_PostalString_1[5];
extern asn_per_constraints_t asn_PER_type_PostalString_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PostalString_H_ */
#include <asn_internal.h>
