/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "asn1/rfc5280-PKIX1Explicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_PresentationAddress_H_
#define	_PresentationAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PresentationAddress */
typedef struct PresentationAddress {
	OCTET_STRING_t	*pSelector	/* OPTIONAL */;
	OCTET_STRING_t	*sSelector	/* OPTIONAL */;
	OCTET_STRING_t	*tSelector	/* OPTIONAL */;
	struct PresentationAddress__nAddresses {
		A_SET_OF(OCTET_STRING_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} nAddresses;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PresentationAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PresentationAddress;
extern asn_SEQUENCE_specifics_t asn_SPC_PresentationAddress_specs_1;
extern asn_TYPE_member_t asn_MBR_PresentationAddress_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _PresentationAddress_H_ */
#include <asn_internal.h>
