/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "asn1/rfc5280-PKIX1Implicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "PrivateKeyUsagePeriod.h"

static asn_TYPE_member_t asn_MBR_PrivateKeyUsagePeriod_1[] = {
	{ ATF_POINTER, 2, offsetof(struct PrivateKeyUsagePeriod, notBefore),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralizedTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notBefore"
		},
	{ ATF_POINTER, 1, offsetof(struct PrivateKeyUsagePeriod, notAfter),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralizedTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notAfter"
		},
};
static const int asn_MAP_PrivateKeyUsagePeriod_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_PrivateKeyUsagePeriod_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PrivateKeyUsagePeriod_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* notBefore */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* notAfter */
};
static asn_SEQUENCE_specifics_t asn_SPC_PrivateKeyUsagePeriod_specs_1 = {
	sizeof(struct PrivateKeyUsagePeriod),
	offsetof(struct PrivateKeyUsagePeriod, _asn_ctx),
	asn_MAP_PrivateKeyUsagePeriod_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_PrivateKeyUsagePeriod_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PrivateKeyUsagePeriod = {
	"PrivateKeyUsagePeriod",
	"PrivateKeyUsagePeriod",
	&asn_OP_SEQUENCE,
	asn_DEF_PrivateKeyUsagePeriod_tags_1,
	sizeof(asn_DEF_PrivateKeyUsagePeriod_tags_1)
		/sizeof(asn_DEF_PrivateKeyUsagePeriod_tags_1[0]), /* 1 */
	asn_DEF_PrivateKeyUsagePeriod_tags_1,	/* Same as above */
	sizeof(asn_DEF_PrivateKeyUsagePeriod_tags_1)
		/sizeof(asn_DEF_PrivateKeyUsagePeriod_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PrivateKeyUsagePeriod_1,
	2,	/* Elements count */
	&asn_SPC_PrivateKeyUsagePeriod_specs_1	/* Additional specs */
};

