/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXqualified88"
 * 	found in "asn1/rfc3739-PKIXqualified88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "QCStatement.h"

asn_TYPE_member_t asn_MBR_QCStatement_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct QCStatement, statementId),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"statementId"
		},
	{ ATF_ANY_TYPE | ATF_POINTER, 1, offsetof(struct QCStatement, statementInfo),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"statementInfo"
		},
};
static const int asn_MAP_QCStatement_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_QCStatement_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_QCStatement_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* statementId */
};
asn_SEQUENCE_specifics_t asn_SPC_QCStatement_specs_1 = {
	sizeof(struct QCStatement),
	offsetof(struct QCStatement, _asn_ctx),
	asn_MAP_QCStatement_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_QCStatement_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_QCStatement = {
	"QCStatement",
	"QCStatement",
	&asn_OP_SEQUENCE,
	asn_DEF_QCStatement_tags_1,
	sizeof(asn_DEF_QCStatement_tags_1)
		/sizeof(asn_DEF_QCStatement_tags_1[0]), /* 1 */
	asn_DEF_QCStatement_tags_1,	/* Same as above */
	sizeof(asn_DEF_QCStatement_tags_1)
		/sizeof(asn_DEF_QCStatement_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_QCStatement_1,
	2,	/* Elements count */
	&asn_SPC_QCStatement_specs_1	/* Additional specs */
};

