/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_RecipientEncryptedKeys_H_
#define	_RecipientEncryptedKeys_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RecipientEncryptedKey;

/* RecipientEncryptedKeys */
typedef struct RecipientEncryptedKeys {
	A_SEQUENCE_OF(struct RecipientEncryptedKey) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RecipientEncryptedKeys_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RecipientEncryptedKeys;
extern asn_SET_OF_specifics_t asn_SPC_RecipientEncryptedKeys_specs_1;
extern asn_TYPE_member_t asn_MBR_RecipientEncryptedKeys_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RecipientEncryptedKey.h"

#endif	/* _RecipientEncryptedKeys_H_ */
#include <asn_internal.h>
