/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_RecipientInfos_H_
#define	_RecipientInfos_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RecipientInfo;

/* RecipientInfos */
typedef struct RecipientInfos {
	A_SET_OF(struct RecipientInfo) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RecipientInfos_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RecipientInfos;
extern asn_SET_OF_specifics_t asn_SPC_RecipientInfos_specs_1;
extern asn_TYPE_member_t asn_MBR_RecipientInfos_1[1];
extern asn_per_constraints_t asn_PER_type_RecipientInfos_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RecipientInfo.h"

#endif	/* _RecipientInfos_H_ */
#include <asn_internal.h>
