/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "RecipientEncryptedKey.h"

asn_TYPE_member_t asn_MBR_RecipientEncryptedKey_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RecipientEncryptedKey, rid),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_KeyAgreeRecipientIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RecipientEncryptedKey, encryptedKey),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_EncryptedKey,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"encryptedKey"
		},
};
static const ber_tlv_tag_t asn_DEF_RecipientEncryptedKey_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RecipientEncryptedKey_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* encryptedKey */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* issuerAndSerialNumber */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* rKeyId */
};
asn_SEQUENCE_specifics_t asn_SPC_RecipientEncryptedKey_specs_1 = {
	sizeof(struct RecipientEncryptedKey),
	offsetof(struct RecipientEncryptedKey, _asn_ctx),
	asn_MAP_RecipientEncryptedKey_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RecipientEncryptedKey = {
	"RecipientEncryptedKey",
	"RecipientEncryptedKey",
	&asn_OP_SEQUENCE,
	asn_DEF_RecipientEncryptedKey_tags_1,
	sizeof(asn_DEF_RecipientEncryptedKey_tags_1)
		/sizeof(asn_DEF_RecipientEncryptedKey_tags_1[0]), /* 1 */
	asn_DEF_RecipientEncryptedKey_tags_1,	/* Same as above */
	sizeof(asn_DEF_RecipientEncryptedKey_tags_1)
		/sizeof(asn_DEF_RecipientEncryptedKey_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RecipientEncryptedKey_1,
	2,	/* Elements count */
	&asn_SPC_RecipientEncryptedKey_specs_1	/* Additional specs */
};

