/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_RecipientIdentifier_H_
#define	_RecipientIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IssuerAndSerialNumber.h"
#include "SubjectKeyIdentifier.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RecipientIdentifier_PR {
	RecipientIdentifier_PR_NOTHING,	/* No components present */
	RecipientIdentifier_PR_issuerAndSerialNumber,
	RecipientIdentifier_PR_subjectKeyIdentifier
} RecipientIdentifier_PR;

/* RecipientIdentifier */
typedef struct RecipientIdentifier {
	RecipientIdentifier_PR present;
	union RecipientIdentifier_u {
		IssuerAndSerialNumber_t	 issuerAndSerialNumber;
		SubjectKeyIdentifier_t	 subjectKeyIdentifier;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RecipientIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RecipientIdentifier;
extern asn_CHOICE_specifics_t asn_SPC_RecipientIdentifier_specs_1;
extern asn_TYPE_member_t asn_MBR_RecipientIdentifier_1[2];
extern asn_per_constraints_t asn_PER_type_RecipientIdentifier_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RecipientIdentifier_H_ */
#include <asn_internal.h>
