/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "RecipientKeyIdentifier.h"

asn_TYPE_member_t asn_MBR_RecipientKeyIdentifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RecipientKeyIdentifier, subjectKeyIdentifier),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_SubjectKeyIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subjectKeyIdentifier"
		},
	{ ATF_POINTER, 2, offsetof(struct RecipientKeyIdentifier, date),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"date"
		},
	{ ATF_POINTER, 1, offsetof(struct RecipientKeyIdentifier, other),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_OtherKeyAttribute,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"other"
		},
};
static const int asn_MAP_RecipientKeyIdentifier_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_RecipientKeyIdentifier_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RecipientKeyIdentifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* subjectKeyIdentifier */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* other */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 1, 0, 0 } /* date */
};
asn_SEQUENCE_specifics_t asn_SPC_RecipientKeyIdentifier_specs_1 = {
	sizeof(struct RecipientKeyIdentifier),
	offsetof(struct RecipientKeyIdentifier, _asn_ctx),
	asn_MAP_RecipientKeyIdentifier_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RecipientKeyIdentifier_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RecipientKeyIdentifier = {
	"RecipientKeyIdentifier",
	"RecipientKeyIdentifier",
	&asn_OP_SEQUENCE,
	asn_DEF_RecipientKeyIdentifier_tags_1,
	sizeof(asn_DEF_RecipientKeyIdentifier_tags_1)
		/sizeof(asn_DEF_RecipientKeyIdentifier_tags_1[0]), /* 1 */
	asn_DEF_RecipientKeyIdentifier_tags_1,	/* Same as above */
	sizeof(asn_DEF_RecipientKeyIdentifier_tags_1)
		/sizeof(asn_DEF_RecipientKeyIdentifier_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RecipientKeyIdentifier_1,
	3,	/* Elements count */
	&asn_SPC_RecipientKeyIdentifier_specs_1	/* Additional specs */
};

