/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "asn1/rfc2560-OCSP.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "ResponderID.h"

static asn_oer_constraints_t asn_OER_type_ResponderID_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ResponderID_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ResponderID_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ResponderID, choice.byName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"byName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ResponderID, choice.byKey),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_KeyHash,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"byKey"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ResponderID_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* byName */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* byKey */
};
asn_CHOICE_specifics_t asn_SPC_ResponderID_specs_1 = {
	sizeof(struct ResponderID),
	offsetof(struct ResponderID, _asn_ctx),
	offsetof(struct ResponderID, present),
	sizeof(((struct ResponderID *)0)->present),
	asn_MAP_ResponderID_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ResponderID = {
	"ResponderID",
	"ResponderID",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ResponderID_constr_1, &asn_PER_type_ResponderID_constr_1, CHOICE_constraint },
	asn_MBR_ResponderID_1,
	2,	/* Elements count */
	&asn_SPC_ResponderID_specs_1	/* Additional specs */
};

