/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "asn1/rfc2560-OCSP.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "ResponseBytes.h"

asn_TYPE_member_t asn_MBR_ResponseBytes_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ResponseBytes, responseType),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"responseType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ResponseBytes, response),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"response"
		},
};
static const ber_tlv_tag_t asn_DEF_ResponseBytes_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ResponseBytes_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* response */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* responseType */
};
asn_SEQUENCE_specifics_t asn_SPC_ResponseBytes_specs_1 = {
	sizeof(struct ResponseBytes),
	offsetof(struct ResponseBytes, _asn_ctx),
	asn_MAP_ResponseBytes_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ResponseBytes = {
	"ResponseBytes",
	"ResponseBytes",
	&asn_OP_SEQUENCE,
	asn_DEF_ResponseBytes_tags_1,
	sizeof(asn_DEF_ResponseBytes_tags_1)
		/sizeof(asn_DEF_ResponseBytes_tags_1[0]), /* 1 */
	asn_DEF_ResponseBytes_tags_1,	/* Same as above */
	sizeof(asn_DEF_ResponseBytes_tags_1)
		/sizeof(asn_DEF_ResponseBytes_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ResponseBytes_1,
	2,	/* Elements count */
	&asn_SPC_ResponseBytes_specs_1	/* Additional specs */
};

