/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_RoleSyntax_H_
#define	_RoleSyntax_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GeneralName.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GeneralNames;

/* RoleSyntax */
typedef struct RoleSyntax {
	struct GeneralNames	*roleAuthority	/* OPTIONAL */;
	GeneralName_t	 roleName;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoleSyntax_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoleSyntax;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeneralNames.h"

#endif	/* _RoleSyntax_H_ */
#include <asn_internal.h>
