/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_SecurityCategory_H_
#define	_SecurityCategory_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SecurityCategory */
typedef struct SecurityCategory {
	OBJECT_IDENTIFIER_t	 type;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityCategory_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityCategory;
extern asn_SEQUENCE_specifics_t asn_SPC_SecurityCategory_specs_1;
extern asn_TYPE_member_t asn_MBR_SecurityCategory_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityCategory_H_ */
#include <asn_internal.h>
