/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXqualified88"
 * 	found in "asn1/rfc3739-PKIXqualified88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_SemanticsInformation_H_
#define	_SemanticsInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NameRegistrationAuthorities;

/* SemanticsInformation */
typedef struct SemanticsInformation {
	OBJECT_IDENTIFIER_t	*semanticsIndentifier	/* OPTIONAL */;
	struct NameRegistrationAuthorities	*nameRegistrationAuthorities	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SemanticsInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SemanticsInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NameRegistrationAuthorities.h"

#endif	/* _SemanticsInformation_H_ */
#include <asn_internal.h>
