/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "asn1/rfc2560-OCSP.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_ServiceLocator_H_
#define	_ServiceLocator_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Name.h"
#include "AuthorityInfoAccessSyntax.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ServiceLocator */
typedef struct ServiceLocator {
	Name_t	 issuer;
	AuthorityInfoAccessSyntax_t	 locator;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServiceLocator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceLocator;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceLocator_H_ */
#include <asn_internal.h>
