/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CertificateTransparencyModule"
 * 	found in "asn1/ct.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_SignedCertificateTimestampList_H_
#define	_SignedCertificateTimestampList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignedCertificateTimestampList */
typedef OCTET_STRING_t	 SignedCertificateTimestampList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignedCertificateTimestampList;
asn_struct_free_f SignedCertificateTimestampList_free;
asn_struct_print_f SignedCertificateTimestampList_print;
asn_constr_check_f SignedCertificateTimestampList_constraint;
ber_type_decoder_f SignedCertificateTimestampList_decode_ber;
der_type_encoder_f SignedCertificateTimestampList_encode_der;
xer_type_decoder_f SignedCertificateTimestampList_decode_xer;
xer_type_encoder_f SignedCertificateTimestampList_encode_xer;
oer_type_decoder_f SignedCertificateTimestampList_decode_oer;
oer_type_encoder_f SignedCertificateTimestampList_encode_oer;
per_type_decoder_f SignedCertificateTimestampList_decode_uper;
per_type_encoder_f SignedCertificateTimestampList_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SignedCertificateTimestampList_H_ */
#include <asn_internal.h>
