/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_SignedData_H_
#define	_SignedData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CMSVersion.h"
#include "DigestAlgorithmIdentifiers.h"
#include "EncapsulatedContentInfo.h"
#include "SignerInfos.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CertificateSet;
struct CertificateRevocationLists;

/* SignedData */
typedef struct SignedData {
	CMSVersion_t	 version;
	DigestAlgorithmIdentifiers_t	 digestAlgorithms;
	EncapsulatedContentInfo_t	 encapContentInfo;
	struct CertificateSet	*certificates	/* OPTIONAL */;
	struct CertificateRevocationLists	*crls	/* OPTIONAL */;
	SignerInfos_t	 signerInfos;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignedData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CertificateSet.h"
#include "CertificateRevocationLists.h"

#endif	/* _SignedData_H_ */
#include <asn_internal.h>
