/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "asn1/rfc3369-CryptographicMessageSyntax.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "SignedData.h"

static asn_TYPE_member_t asn_MBR_SignedData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SignedData, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_CMSVersion,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignedData, digestAlgorithms),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_DigestAlgorithmIdentifiers,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"digestAlgorithms"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignedData, encapContentInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EncapsulatedContentInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"encapContentInfo"
		},
	{ ATF_POINTER, 2, offsetof(struct SignedData, certificates),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CertificateSet,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certificates"
		},
	{ ATF_POINTER, 1, offsetof(struct SignedData, crls),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CertificateRevocationLists,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crls"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignedData, signerInfos),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_SignerInfos,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signerInfos"
		},
};
static const int asn_MAP_SignedData_oms_1[] = { 3, 4 };
static const ber_tlv_tag_t asn_DEF_SignedData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SignedData_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* encapContentInfo */
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 1, 0, 1 }, /* digestAlgorithms */
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 5, -1, 0 }, /* signerInfos */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 3, 0, 0 }, /* certificates */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 4, 0, 0 } /* crls */
};
static asn_SEQUENCE_specifics_t asn_SPC_SignedData_specs_1 = {
	sizeof(struct SignedData),
	offsetof(struct SignedData, _asn_ctx),
	asn_MAP_SignedData_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_SignedData_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SignedData = {
	"SignedData",
	"SignedData",
	&asn_OP_SEQUENCE,
	asn_DEF_SignedData_tags_1,
	sizeof(asn_DEF_SignedData_tags_1)
		/sizeof(asn_DEF_SignedData_tags_1[0]), /* 1 */
	asn_DEF_SignedData_tags_1,	/* Same as above */
	sizeof(asn_DEF_SignedData_tags_1)
		/sizeof(asn_DEF_SignedData_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SignedData_1,
	6,	/* Elements count */
	&asn_SPC_SignedData_specs_1	/* Additional specs */
};

