/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "asn1/rfc2560-OCSP.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "SingleResponse.h"

asn_TYPE_member_t asn_MBR_SingleResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SingleResponse, certID),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CertID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SingleResponse, certStatus),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_CertStatus,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SingleResponse, thisUpdate),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"thisUpdate"
		},
	{ ATF_POINTER, 2, offsetof(struct SingleResponse, nextUpdate),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GeneralizedTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nextUpdate"
		},
	{ ATF_POINTER, 1, offsetof(struct SingleResponse, singleExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Extensions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"singleExtensions"
		},
};
static const int asn_MAP_SingleResponse_oms_1[] = { 3, 4 };
static const ber_tlv_tag_t asn_DEF_SingleResponse_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SingleResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* certID */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 2, 0, 0 }, /* thisUpdate */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 1 }, /* good */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 3, -1, 0 }, /* nextUpdate */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 1 }, /* revoked */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 4, -1, 0 }, /* singleExtensions */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* unknown */
};
asn_SEQUENCE_specifics_t asn_SPC_SingleResponse_specs_1 = {
	sizeof(struct SingleResponse),
	offsetof(struct SingleResponse, _asn_ctx),
	asn_MAP_SingleResponse_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_SingleResponse_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SingleResponse = {
	"SingleResponse",
	"SingleResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_SingleResponse_tags_1,
	sizeof(asn_DEF_SingleResponse_tags_1)
		/sizeof(asn_DEF_SingleResponse_tags_1[0]), /* 1 */
	asn_DEF_SingleResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_SingleResponse_tags_1)
		/sizeof(asn_DEF_SingleResponse_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SingleResponse_1,
	5,	/* Elements count */
	&asn_SPC_SingleResponse_specs_1	/* Additional specs */
};

