/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecureMimeMessageV3dot1"
 * 	found in "asn1/rfc3851-SecureMimeMessageV3dot1.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "SMIMECapability.h"

asn_TYPE_member_t asn_MBR_SMIMECapability_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SMIMECapability, capabilityID),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"capabilityID"
		},
	{ ATF_ANY_TYPE | ATF_POINTER, 1, offsetof(struct SMIMECapability, parameters),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"parameters"
		},
};
static const int asn_MAP_SMIMECapability_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_SMIMECapability_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SMIMECapability_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* capabilityID */
};
asn_SEQUENCE_specifics_t asn_SPC_SMIMECapability_specs_1 = {
	sizeof(struct SMIMECapability),
	offsetof(struct SMIMECapability, _asn_ctx),
	asn_MAP_SMIMECapability_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_SMIMECapability_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SMIMECapability = {
	"SMIMECapability",
	"SMIMECapability",
	&asn_OP_SEQUENCE,
	asn_DEF_SMIMECapability_tags_1,
	sizeof(asn_DEF_SMIMECapability_tags_1)
		/sizeof(asn_DEF_SMIMECapability_tags_1[0]), /* 1 */
	asn_DEF_SMIMECapability_tags_1,	/* Same as above */
	sizeof(asn_DEF_SMIMECapability_tags_1)
		/sizeof(asn_DEF_SMIMECapability_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SMIMECapability_1,
	2,	/* Elements count */
	&asn_SPC_SMIMECapability_specs_1	/* Additional specs */
};

