/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "asn1/rfc5280-PKIX1Explicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "SubjectPublicKeyInfo.h"

asn_TYPE_member_t asn_MBR_SubjectPublicKeyInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SubjectPublicKeyInfo, algorithm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgorithmIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"algorithm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubjectPublicKeyInfo, subjectPublicKey),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subjectPublicKey"
		},
};
static const ber_tlv_tag_t asn_DEF_SubjectPublicKeyInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SubjectPublicKeyInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, 0, 0 }, /* subjectPublicKey */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* algorithm */
};
asn_SEQUENCE_specifics_t asn_SPC_SubjectPublicKeyInfo_specs_1 = {
	sizeof(struct SubjectPublicKeyInfo),
	offsetof(struct SubjectPublicKeyInfo, _asn_ctx),
	asn_MAP_SubjectPublicKeyInfo_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SubjectPublicKeyInfo = {
	"SubjectPublicKeyInfo",
	"SubjectPublicKeyInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_SubjectPublicKeyInfo_tags_1,
	sizeof(asn_DEF_SubjectPublicKeyInfo_tags_1)
		/sizeof(asn_DEF_SubjectPublicKeyInfo_tags_1[0]), /* 1 */
	asn_DEF_SubjectPublicKeyInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_SubjectPublicKeyInfo_tags_1)
		/sizeof(asn_DEF_SubjectPublicKeyInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SubjectPublicKeyInfo_1,
	2,	/* Elements count */
	&asn_SPC_SubjectPublicKeyInfo_specs_1	/* Additional specs */
};

