/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "Target.h"

static asn_oer_constraints_t asn_OER_type_Target_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Target_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_Target_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Target, choice.targetName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GeneralName,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"targetName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Target, choice.targetGroup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GeneralName,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"targetGroup"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Target, choice.targetCert),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TargetCert,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"targetCert"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Target_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* targetName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* targetGroup */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* targetCert */
};
asn_CHOICE_specifics_t asn_SPC_Target_specs_1 = {
	sizeof(struct Target),
	offsetof(struct Target, _asn_ctx),
	offsetof(struct Target, present),
	sizeof(((struct Target *)0)->present),
	asn_MAP_Target_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Target = {
	"Target",
	"Target",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Target_constr_1, &asn_PER_type_Target_constr_1, CHOICE_constraint },
	asn_MBR_Target_1,
	3,	/* Elements count */
	&asn_SPC_Target_specs_1	/* Additional specs */
};

