/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_Target_H_
#define	_Target_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GeneralName.h"
#include "TargetCert.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Target_PR {
	Target_PR_NOTHING,	/* No components present */
	Target_PR_targetName,
	Target_PR_targetGroup,
	Target_PR_targetCert
} Target_PR;

/* Target */
typedef struct Target {
	Target_PR present;
	union Target_u {
		GeneralName_t	 targetName;
		GeneralName_t	 targetGroup;
		TargetCert_t	 targetCert;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Target_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Target;
extern asn_CHOICE_specifics_t asn_SPC_Target_specs_1;
extern asn_TYPE_member_t asn_MBR_Target_1[3];
extern asn_per_constraints_t asn_PER_type_Target_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Target_H_ */
#include <asn_internal.h>
