/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "Targets.h"

asn_TYPE_member_t asn_MBR_Targets_1[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Target,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_Targets_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_Targets_specs_1 = {
	sizeof(struct Targets),
	offsetof(struct Targets, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
asn_TYPE_descriptor_t asn_DEF_Targets = {
	"Targets",
	"Targets",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_Targets_tags_1,
	sizeof(asn_DEF_Targets_tags_1)
		/sizeof(asn_DEF_Targets_tags_1[0]), /* 1 */
	asn_DEF_Targets_tags_1,	/* Same as above */
	sizeof(asn_DEF_Targets_tags_1)
		/sizeof(asn_DEF_Targets_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_Targets_1,
	1,	/* Single element */
	&asn_SPC_Targets_specs_1	/* Additional specs */
};

