/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "asn1/rfc2560-OCSP.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_TBSRequest_H_
#define	_TBSRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OCSP_Version.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GeneralName;
struct Extensions;
struct Request;

/* TBSRequest */
typedef struct TBSRequest {
	OCSP_Version_t	*version	/* DEFAULT 0 */;
	struct GeneralName	*requestorName	/* OPTIONAL */;
	struct TBSRequest__requestList {
		A_SEQUENCE_OF(struct Request) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} requestList;
	struct Extensions	*requestExtensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TBSRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TBSRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_TBSRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_TBSRequest_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeneralName.h"
#include "Extensions.h"
#include "Request.h"

#endif	/* _TBSRequest_H_ */
#include <asn_internal.h>
