/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CABFSelectedAttributeTypes"
 * 	found in "asn1/cabfev.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "TorServiceDescriptorHash.h"

asn_TYPE_member_t asn_MBR_TorServiceDescriptorHash_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TorServiceDescriptorHash, onionURI),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"onionURI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TorServiceDescriptorHash, algorithm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgorithmIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"algorithm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TorServiceDescriptorHash, subjectPublicKeyHash),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subjectPublicKeyHash"
		},
};
static const ber_tlv_tag_t asn_DEF_TorServiceDescriptorHash_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TorServiceDescriptorHash_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, 0, 0 }, /* subjectPublicKeyHash */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 0, 0, 0 }, /* onionURI */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* algorithm */
};
asn_SEQUENCE_specifics_t asn_SPC_TorServiceDescriptorHash_specs_1 = {
	sizeof(struct TorServiceDescriptorHash),
	offsetof(struct TorServiceDescriptorHash, _asn_ctx),
	asn_MAP_TorServiceDescriptorHash_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TorServiceDescriptorHash = {
	"TorServiceDescriptorHash",
	"TorServiceDescriptorHash",
	&asn_OP_SEQUENCE,
	asn_DEF_TorServiceDescriptorHash_tags_1,
	sizeof(asn_DEF_TorServiceDescriptorHash_tags_1)
		/sizeof(asn_DEF_TorServiceDescriptorHash_tags_1[0]), /* 1 */
	asn_DEF_TorServiceDescriptorHash_tags_1,	/* Same as above */
	sizeof(asn_DEF_TorServiceDescriptorHash_tags_1)
		/sizeof(asn_DEF_TorServiceDescriptorHash_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TorServiceDescriptorHash_1,
	3,	/* Elements count */
	&asn_SPC_TorServiceDescriptorHash_specs_1	/* Additional specs */
};

