/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXqualified88"
 * 	found in "asn1/rfc3739-PKIXqualified88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_TypeOfBiometricData_H_
#define	_TypeOfBiometricData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PredefinedBiometricType.h"
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TypeOfBiometricData_PR {
	TypeOfBiometricData_PR_NOTHING,	/* No components present */
	TypeOfBiometricData_PR_predefinedBiometricType,
	TypeOfBiometricData_PR_biometricDataOid
} TypeOfBiometricData_PR;

/* TypeOfBiometricData */
typedef struct TypeOfBiometricData {
	TypeOfBiometricData_PR present;
	union TypeOfBiometricData_u {
		PredefinedBiometricType_t	 predefinedBiometricType;
		OBJECT_IDENTIFIER_t	 biometricDataOid;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TypeOfBiometricData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TypeOfBiometricData;
extern asn_CHOICE_specifics_t asn_SPC_TypeOfBiometricData_specs_1;
extern asn_TYPE_member_t asn_MBR_TypeOfBiometricData_1[2];
extern asn_per_constraints_t asn_PER_type_TypeOfBiometricData_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TypeOfBiometricData_H_ */
#include <asn_internal.h>
