/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXqualified88"
 * 	found in "asn1/rfc3739-PKIXqualified88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "TypeOfBiometricData.h"

static asn_oer_constraints_t asn_OER_type_TypeOfBiometricData_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_TypeOfBiometricData_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_TypeOfBiometricData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TypeOfBiometricData, choice.predefinedBiometricType),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_PredefinedBiometricType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"predefinedBiometricType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeOfBiometricData, choice.biometricDataOid),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"biometricDataOid"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_TypeOfBiometricData_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* predefinedBiometricType */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, 0, 0 } /* biometricDataOid */
};
asn_CHOICE_specifics_t asn_SPC_TypeOfBiometricData_specs_1 = {
	sizeof(struct TypeOfBiometricData),
	offsetof(struct TypeOfBiometricData, _asn_ctx),
	offsetof(struct TypeOfBiometricData, present),
	sizeof(((struct TypeOfBiometricData *)0)->present),
	asn_MAP_TypeOfBiometricData_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TypeOfBiometricData = {
	"TypeOfBiometricData",
	"TypeOfBiometricData",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_TypeOfBiometricData_constr_1, &asn_PER_type_TypeOfBiometricData_constr_1, CHOICE_constraint },
	asn_MBR_TypeOfBiometricData_1,
	2,	/* Elements count */
	&asn_SPC_TypeOfBiometricData_specs_1	/* Additional specs */
};

