/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OtherAttributesModule"
 * 	found in "asn1/otherattrs.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#include "UnstructuredName.h"

static int check_permitted_alphabet_2(const void *sptr) {
	/* The underlying type is IA5String */
	const IA5String_t *st = (const IA5String_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!(cv <= 127)) return -1;
	}
	return 0;
}

static int
memb_ia5String_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const IA5String_t *st = (const IA5String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 255)
		 && !check_permitted_alphabet_2(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_ia5String_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..255)) */};
static asn_per_constraints_t asn_PER_memb_ia5String_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  127 }	/* (0..127) */,
	{ APC_CONSTRAINED,	 8,  8,  1,  255 }	/* (SIZE(1..255)) */,
	0, 0	/* No PER character map necessary */
};
static asn_oer_constraints_t asn_OER_type_UnstructuredName_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_UnstructuredName_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_UnstructuredName_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UnstructuredName, choice.ia5String),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,
		{ &asn_OER_memb_ia5String_constr_2, &asn_PER_memb_ia5String_constr_2,  memb_ia5String_constraint_1 },
		0, 0, /* No default value */
		"ia5String"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UnstructuredName, choice.directoryString),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_UnstructuredNameDirectoryString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"directoryString"
		},
};
static const unsigned asn_MAP_UnstructuredName_to_canonical_1[] = { 1, 0 };
static const unsigned asn_MAP_UnstructuredName_from_canonical_1[] = { 1, 0 };
static const asn_TYPE_tag2member_t asn_MAP_UnstructuredName_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 1, 0, 0 }, /* utf8String */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 1, 0, 0 }, /* printableString */
    { (ASN_TAG_CLASS_UNIVERSAL | (20 << 2)), 1, 0, 0 }, /* teletexString */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 0, 0, 0 }, /* ia5String */
    { (ASN_TAG_CLASS_UNIVERSAL | (28 << 2)), 1, 0, 0 }, /* universalString */
    { (ASN_TAG_CLASS_UNIVERSAL | (30 << 2)), 1, 0, 0 } /* bmpString */
};
static asn_CHOICE_specifics_t asn_SPC_UnstructuredName_specs_1 = {
	sizeof(struct UnstructuredName),
	offsetof(struct UnstructuredName, _asn_ctx),
	offsetof(struct UnstructuredName, present),
	sizeof(((struct UnstructuredName *)0)->present),
	asn_MAP_UnstructuredName_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_UnstructuredName_to_canonical_1,
	asn_MAP_UnstructuredName_from_canonical_1,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UnstructuredName = {
	"UnstructuredName",
	"UnstructuredName",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_UnstructuredName_constr_1, &asn_PER_type_UnstructuredName_constr_1, CHOICE_constraint },
	asn_MBR_UnstructuredName_1,
	2,	/* Elements count */
	&asn_SPC_UnstructuredName_specs_1	/* Additional specs */
};

