/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OtherAttributesModule"
 * 	found in "asn1/otherattrs.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_UnstructuredNameDirectoryString_H_
#define	_UnstructuredNameDirectoryString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <TeletexString.h>
#include <PrintableString.h>
#include <UniversalString.h>
#include <UTF8String.h>
#include <BMPString.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UnstructuredNameDirectoryString_PR {
	UnstructuredNameDirectoryString_PR_NOTHING,	/* No components present */
	UnstructuredNameDirectoryString_PR_teletexString,
	UnstructuredNameDirectoryString_PR_printableString,
	UnstructuredNameDirectoryString_PR_universalString,
	UnstructuredNameDirectoryString_PR_utf8String,
	UnstructuredNameDirectoryString_PR_bmpString
} UnstructuredNameDirectoryString_PR;

/* UnstructuredNameDirectoryString */
typedef struct UnstructuredNameDirectoryString {
	UnstructuredNameDirectoryString_PR present;
	union UnstructuredNameDirectoryString_u {
		TeletexString_t	 teletexString;
		PrintableString_t	 printableString;
		UniversalString_t	 universalString;
		UTF8String_t	 utf8String;
		BMPString_t	 bmpString;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UnstructuredNameDirectoryString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnstructuredNameDirectoryString;
extern asn_CHOICE_specifics_t asn_SPC_UnstructuredNameDirectoryString_specs_1;
extern asn_TYPE_member_t asn_MBR_UnstructuredNameDirectoryString_1[5];
extern asn_per_constraints_t asn_PER_type_UnstructuredNameDirectoryString_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _UnstructuredNameDirectoryString_H_ */
#include <asn_internal.h>
