/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "asn1/rfc5280-PKIX1Implicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_UserNotice_H_
#define	_UserNotice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NoticeReference;
struct DisplayText;

/* UserNotice */
typedef struct UserNotice {
	struct NoticeReference	*noticeRef	/* OPTIONAL */;
	struct DisplayText	*explicitText	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UserNotice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UserNotice;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NoticeReference.h"
#include "DisplayText.h"

#endif	/* _UserNotice_H_ */
#include <asn_internal.h>
