/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "asn1/rfc3281-PKIXAttributeCertificate.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_V2Form_H_
#define	_V2Form_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GeneralNames;
struct IssuerSerial;
struct ObjectDigestInfo;

/* V2Form */
typedef struct V2Form {
	struct GeneralNames	*issuerName	/* OPTIONAL */;
	struct IssuerSerial	*baseCertificateID	/* OPTIONAL */;
	struct ObjectDigestInfo	*objectDigestInfo	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} V2Form_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_V2Form;
extern asn_SEQUENCE_specifics_t asn_SPC_V2Form_specs_1;
extern asn_TYPE_member_t asn_MBR_V2Form_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeneralNames.h"
#include "IssuerSerial.h"
#include "ObjectDigestInfo.h"

#endif	/* _V2Form_H_ */
#include <asn_internal.h>
