/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "asn1/rfc5280-PKIX1Explicit88.asn1"
 * 	`asn1c -S /home/fotisl/Projects/revlintsynt/asn1c/skeletons -pdu=all -fwide-types -fcompound-names`
 */

#ifndef	_X520Title_H_
#define	_X520Title_H_


#include <asn_application.h>

/* Including external dependencies */
#include <TeletexString.h>
#include <PrintableString.h>
#include <UniversalString.h>
#include <UTF8String.h>
#include <BMPString.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum X520Title_PR {
	X520Title_PR_NOTHING,	/* No components present */
	X520Title_PR_teletexString,
	X520Title_PR_printableString,
	X520Title_PR_universalString,
	X520Title_PR_utf8String,
	X520Title_PR_bmpString
} X520Title_PR;

/* X520Title */
typedef struct X520Title {
	X520Title_PR present;
	union X520Title_u {
		TeletexString_t	 teletexString;
		PrintableString_t	 printableString;
		UniversalString_t	 universalString;
		UTF8String_t	 utf8String;
		BMPString_t	 bmpString;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} X520Title_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X520Title;

#ifdef __cplusplus
}
#endif

#endif	/* _X520Title_H_ */
#include <asn_internal.h>
